table 'Data Refresh'
	isHidden
	lineageTag: 5d7b604e-97b7-4d33-ae36-90dbf7bda192

	column CurrentDateTime
		dataType: string
		isHidden
		lineageTag: 26d24d4e-d512-4cd9-91fa-f11f2507e70b
		summarizeBy: none
		sourceColumn: CurrentDateTime

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: ff24430d-3895-4f8d-b799-b5648cf363b4
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 39949fd6-2267-48b7-a9ac-1e267e700dc0
		summarizeBy: none
		sourceColumn: Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	partition 'Data Refresh' = m
		mode: import
		source =
				let
				    // Fabric/Power BI Service runs in UTC — DateTime.LocalNow() returns UTC, not local time.
				    // DateTimeZone.SwitchZone converts UTC to Central Time with automatic DST handling.
				    UtcNow    = DateTimeZone.UtcNow(),
				    UtcDT     = DateTimeZone.RemoveZone(UtcNow),
				    CurYear   = Date.Year(DateTime.Date(UtcDT)),
				    Mar1      = #date(CurYear, 3, 1),
				    Sun1Mar   = Date.AddDays(Mar1, Number.Mod(7 - Date.DayOfWeek(Mar1, Day.Sunday), 7)),
				    DstStart  = #datetime(CurYear, 3, Date.Day(Date.AddDays(Sun1Mar, 7)), 8, 0, 0),
				    Nov1      = #date(CurYear, 11, 1),
				    Sun1Nov   = Date.AddDays(Nov1, Number.Mod(7 - Date.DayOfWeek(Nov1, Day.Sunday), 7)),
				    DstEnd    = #datetime(CurYear, 11, Date.Day(Sun1Nov), 7, 0, 0),
				    OffsetHrs = if UtcDT >= DstStart and UtcDT < DstEnd then -5 else -6,
				    LocalDT   = DateTimeZone.RemoveZone(DateTimeZone.SwitchZone(UtcNow, OffsetHrs, 0)),
				    Source    = #table({"CurrentDateTime"}, {{LocalDT}}),
				    AddDate   = Table.DuplicateColumn(Source, "CurrentDateTime", "Date"),
				    AddTime   = Table.DuplicateColumn(AddDate, "Date", "Time"),
				    ChgTypes  = Table.TransformColumnTypes(AddTime, {{"Date", type date}, {"Time", type time}})
				in
				    ChgTypes

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

