table dim_CustomerList
	lineageTag: bfe6cf9c-3c60-4fbc-ae7a-34a08f873dad

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: 7f4b1d50-eea8-4745-a60f-bd861f5a8b5a
		summarizeBy: count
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column AccountNumber
		dataType: string
		lineageTag: e1520f3f-603d-4bc1-9884-71dbff1d04b2
		summarizeBy: none
		sourceColumn: AccountNumber

		annotation SummarizationSetBy = Automatic

	column AccountNumberText
		dataType: string
		lineageTag: d7eb90c5-1d0a-4f1c-adc4-285708963644
		summarizeBy: none
		sourceColumn: AccountNumberText

		annotation SummarizationSetBy = Automatic

	column CustomerNumber
		dataType: string
		lineageTag: b3be8c41-e9d0-424e-9e91-642eeb2cc15a
		summarizeBy: none
		sourceColumn: CustomerNumber

		annotation SummarizationSetBy = Automatic

	column CustomerNumberText
		dataType: string
		lineageTag: 43a56d4a-b382-44a0-a137-c70f0fa90a0f
		summarizeBy: none
		sourceColumn: CustomerNumberText

		annotation SummarizationSetBy = Automatic

	column ContactID
		dataType: string
		lineageTag: fdc52284-4a4a-46e4-aa7f-7d570d648524
		summarizeBy: none
		sourceColumn: ContactID

		annotation SummarizationSetBy = Automatic

	column DisplayName
		dataType: string
		lineageTag: 8cbe3759-5edd-44e0-9b08-848fb45b3e1d
		summarizeBy: none
		sourceColumn: DisplayName

		annotation SummarizationSetBy = Automatic

	column CustomerName
		dataType: string
		lineageTag: d006597d-4a7f-4669-ba42-af91d608f5f9
		summarizeBy: none
		sourceColumn: CustomerName

		annotation SummarizationSetBy = Automatic

	column PrimaryName
		dataType: string
		lineageTag: 111245af-4b94-472c-b9f2-46e7bb6f1902
		summarizeBy: none
		sourceColumn: PrimaryName

		annotation SummarizationSetBy = Automatic

	column CompanyName
		dataType: string
		lineageTag: 7b4512b1-cb73-4b37-92ab-a16c1757c313
		summarizeBy: none
		sourceColumn: CompanyName

		annotation SummarizationSetBy = Automatic

	column FirstName
		dataType: string
		lineageTag: aea53128-70ca-45bd-aa4b-30abf2a1a0a7
		summarizeBy: none
		sourceColumn: FirstName

		annotation SummarizationSetBy = Automatic

	column LastName
		dataType: string
		lineageTag: 0f448b8c-5e63-4abe-99b8-37ef384e4c80
		summarizeBy: none
		sourceColumn: LastName

		annotation SummarizationSetBy = Automatic

	column FullName
		dataType: string
		lineageTag: c6e3db42-348b-49e9-b6fa-3faff0b0042e
		summarizeBy: none
		sourceColumn: FullName

		annotation SummarizationSetBy = Automatic

	column TradeType
		dataType: string
		lineageTag: b91a3e57-21b2-4ca5-8e65-948dec1bdfee
		summarizeBy: none
		sourceColumn: TradeType

		annotation SummarizationSetBy = Automatic

	column CustomerTypeDescription
		dataType: string
		lineageTag: 02487719-18a4-4c33-98be-0c5d298df909
		summarizeBy: none
		sourceColumn: CustomerTypeDescription

		annotation SummarizationSetBy = Automatic

	column StatusCode
		dataType: string
		lineageTag: 526cf0cc-ecec-403b-8e63-b07c109744ca
		summarizeBy: none
		sourceColumn: StatusCode

		annotation SummarizationSetBy = Automatic

	column AccountStatus
		dataType: string
		lineageTag: 71380a44-ca4b-4220-85db-98ee45eb41be
		summarizeBy: none
		sourceColumn: AccountStatus

		annotation SummarizationSetBy = Automatic

	column AccountType
		dataType: string
		lineageTag: 0d887d0e-9332-4122-afaa-42d5271532ef
		summarizeBy: none
		sourceColumn: AccountType

		annotation SummarizationSetBy = Automatic

	column Territory
		dataType: string
		lineageTag: c5305c47-b504-4d2b-adc2-3f048629e827
		summarizeBy: none
		sourceColumn: Territory

		annotation SummarizationSetBy = Automatic

	column CreditLimit
		dataType: double
		lineageTag: a4ba7565-f82a-4d71-9ae2-8c7264d9f4e5
		summarizeBy: sum
		sourceColumn: CreditLimit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AccountBalance
		dataType: double
		lineageTag: 5f2b75ae-1384-42af-9f95-80ed13fe27e2
		summarizeBy: sum
		sourceColumn: AccountBalance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CreditTerm
		dataType: string
		lineageTag: 64fd049d-4280-42cd-8a42-6a1b267f5e9a
		summarizeBy: none
		sourceColumn: CreditTerm

		annotation SummarizationSetBy = Automatic

	column PaymentMethod
		dataType: string
		lineageTag: 6436aa6c-f2a3-4512-81b4-30869929deac
		summarizeBy: none
		sourceColumn: PaymentMethod

		annotation SummarizationSetBy = Automatic

	column PriceLevel
		dataType: string
		lineageTag: 98937be1-1946-4c17-873f-d03e3ac4be40
		summarizeBy: none
		sourceColumn: PriceLevel

		annotation SummarizationSetBy = Automatic

	column Street
		dataType: string
		lineageTag: 5b5f6f56-4904-4158-be21-a6a34de80d25
		summarizeBy: none
		sourceColumn: Street

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: da2392af-cc5a-4a32-89e5-56ad3083ada6
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 7b1d1502-4905-431b-a1da-36aba9dfcb4f
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column PostalCode
		dataType: string
		lineageTag: f9ed7393-a14f-45f2-b062-11dff7933b3a
		summarizeBy: none
		sourceColumn: PostalCode

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: a9be49a1-f77f-4b41-9aa6-241a6500c4c7
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Email
		dataType: string
		lineageTag: d9be2efb-ffd1-4db5-9462-380526f9e862
		summarizeBy: none
		sourceColumn: Email

		annotation SummarizationSetBy = Automatic

	column PrimaryPhone
		dataType: string
		lineageTag: 0d90a9d2-4d81-4b8c-a14d-91167ed8c492
		summarizeBy: none
		sourceColumn: PrimaryPhone

		annotation SummarizationSetBy = Automatic

	column BusinessPhone
		dataType: string
		lineageTag: ca2a01ee-188d-4c23-89df-3748354bdd7f
		summarizeBy: none
		sourceColumn: BusinessPhone

		annotation SummarizationSetBy = Automatic

	column MobilePhone
		dataType: string
		lineageTag: 8b8f7947-251f-4e81-a539-761860029751
		summarizeBy: none
		sourceColumn: MobilePhone

		annotation SummarizationSetBy = Automatic

	column IsCompany
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8b1d461c-ad56-46e3-ba6c-5585f5945f5e
		summarizeBy: none
		sourceColumn: IsCompany

		annotation SummarizationSetBy = Automatic

	column HasCreditLimit
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 75821c81-6677-42da-a878-e6e9e09f237b
		summarizeBy: none
		sourceColumn: HasCreditLimit

		annotation SummarizationSetBy = Automatic

	column DiscountType
		dataType: string
		lineageTag: 8dcb02d7-6d57-4127-b87a-0041ea2912da
		summarizeBy: none
		sourceColumn: DiscountType

		annotation SummarizationSetBy = Automatic

	column TaxExemptNumber
		dataType: string
		lineageTag: 1bc5779d-f198-429b-8b91-4313fb440c7a
		summarizeBy: none
		sourceColumn: TaxExemptNumber

		annotation SummarizationSetBy = Automatic

	column CustomerNotes
		dataType: string
		lineageTag: 30cb933e-e17e-4678-9ea8-134b34c86cd0
		summarizeBy: none
		sourceColumn: CustomerNotes

		annotation SummarizationSetBy = Automatic

	column Aging30
		dataType: double
		lineageTag: db3b0879-6279-45b8-856c-6ff07818c1d6
		summarizeBy: sum
		sourceColumn: Aging30

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Aging60
		dataType: double
		lineageTag: dd5143dc-1fca-4a95-9a54-801a6ef08ea2
		summarizeBy: sum
		sourceColumn: Aging60

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Aging90
		dataType: double
		lineageTag: 9d3314f5-ff3d-4c8e-a37a-7cdbaa68812c
		summarizeBy: sum
		sourceColumn: Aging90

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Street2
		dataType: string
		lineageTag: da193d9f-4ce9-473f-8039-0c3f63bdc92c
		summarizeBy: none
		sourceColumn: Street2

		annotation SummarizationSetBy = Automatic

	column HomePhone
		dataType: string
		lineageTag: 46b8bbe5-9db3-4269-afea-7a2e0706b068
		summarizeBy: none
		sourceColumn: HomePhone

		annotation SummarizationSetBy = Automatic

	column Account_Class
		dataType: string
		lineageTag: 69fcb31d-73da-4030-a675-8f8b1e4115b7
		summarizeBy: none
		sourceColumn: Account_Class

		annotation SummarizationSetBy = Automatic

	column ContactClass
		dataType: string
		lineageTag: daea9edb-6232-416f-babb-6fbd4352c2df
		summarizeBy: none
		sourceColumn: ContactClass

		annotation SummarizationSetBy = Automatic

	column IsKeyCustomer
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7591b661-f6ba-4d8e-be8f-6436d44aa776
		summarizeBy: none
		sourceColumn: IsKeyCustomer

		annotation SummarizationSetBy = Automatic

	column CreditUtilization
		dataType: double
		lineageTag: 9503103a-f43d-48df-85fb-6fbccf156bb4
		summarizeBy: sum
		sourceColumn: CreditUtilization

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FinancialRiskLevel
		dataType: string
		lineageTag: bd08806b-b3b4-463f-8c08-c37a2a3a0bc6
		summarizeBy: none
		sourceColumn: FinancialRiskLevel

		annotation SummarizationSetBy = Automatic

	column HasOverdueBalance
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 594d6c65-bf84-4aa2-b92b-0fa84e01bdc6
		summarizeBy: none
		sourceColumn: HasOverdueBalance

		annotation SummarizationSetBy = Automatic

	column CustomerTier
		dataType: string
		lineageTag: f69073ff-8aef-4d68-8b49-965946d25fa9
		summarizeBy: none
		sourceColumn: CustomerTier

		annotation SummarizationSetBy = Automatic

	column IsHighValue
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8444c700-80ad-4b79-b10d-3f236992947d
		summarizeBy: none
		sourceColumn: IsHighValue

		annotation SummarizationSetBy = Automatic

	column IsMarketingEligible
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 925def11-d76a-4c17-aef0-7ff8b098d36e
		summarizeBy: none
		sourceColumn: IsMarketingEligible

		annotation SummarizationSetBy = Automatic

	column PreferredContactMethod
		dataType: string
		lineageTag: d455d9b9-1e08-4d67-affb-b1c5aad9c7ce
		summarizeBy: none
		sourceColumn: PreferredContactMethod

		annotation SummarizationSetBy = Automatic

	column DataQualityScore
		dataType: double
		lineageTag: 34779257-0559-4a5a-bb2b-b166384e37c8
		summarizeBy: sum
		sourceColumn: DataQualityScore

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition dim_CustomerList = m
		mode: import
		source =
				let
				    Source = Sql.Database("xcrafcusadsu3d3wi4anbgp6we-gxnyznhdptpenfw724g3o5sjzm.datawarehouse.fabric.microsoft.com", "LH_Master_Data"),
				    dbo_dim_CustomerList = Source{[Schema="dbo",Item="dim_CustomerList"]}[Data],
				    FilterValidCustomers = Table.SelectRows(dbo_dim_CustomerList, each [CustomerNumber] <> null and [CustomerNumber] <> "")
				in
				    FilterValidCustomers

