table Parts_Open_Tickets
	lineageTag: 02124ea8-d252-4cfd-81e8-5084dbc03116

	column Location
		dataType: string
		lineageTag: 9a7cc829-cb13-492c-ae3c-ee4c5814a2d2
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column Location_Name
		dataType: string
		lineageTag: 204a46a1-8c1b-4d03-8b42-318325673b5a
		summarizeBy: none
		sourceColumn: Location_Name

		annotation SummarizationSetBy = Automatic

	column Order_No
		dataType: int64
		formatString: 0
		lineageTag: a67ea8de-f642-4450-bf62-c1aa47fa1537
		summarizeBy: none
		sourceColumn: Order_No

		annotation SummarizationSetBy = Automatic

	column Invoice_Type
		dataType: string
		lineageTag: 0243db9e-1c45-49ec-a0b5-40f03d16f56d
		summarizeBy: none
		sourceColumn: Invoice_Type

		annotation SummarizationSetBy = Automatic

	column Order_Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: e422dfea-fc44-46bf-aee2-cfa83ffd0ba5
		summarizeBy: none
		sourceColumn: Order_Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Days_Open
		dataType: int64
		formatString: 0
		lineageTag: a84e78b1-1764-4f63-b85c-abc682ae8b48
		summarizeBy: sum
		sourceColumn: Days_Open

		annotation SummarizationSetBy = Automatic

	column Aging
		dataType: string
		lineageTag: eabaffab-49f6-4214-abf8-c582468a2033
		summarizeBy: none
		sourceColumn: Aging
		sortByColumn: Aging_Sort_Order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column #_Parts_On_Order
		dataType: double
		lineageTag: af85474d-0c0d-4bc7-b22f-471c7ff5a965
		summarizeBy: sum
		sourceColumn: #_Parts_On_Order

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column #_On_Back_Order
		dataType: double
		lineageTag: db222c30-d6e5-463b-af2d-7c1b475bc100
		summarizeBy: sum
		sourceColumn: #_On_Back_Order

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Order_Total_$$
		dataType: double
		lineageTag: 2580a580-16bf-49c0-97af-20980ad358e8
		summarizeBy: sum
		sourceColumn: Order_Total_$$

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Deposit
		dataType: double
		lineageTag: 2052757b-bba1-4ae1-9a4c-e23c4cb23856
		summarizeBy: sum
		sourceColumn: Deposit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Salesman
		dataType: string
		lineageTag: 6353da27-9c1f-4767-bec4-d9dee4b96a66
		summarizeBy: none
		sourceColumn: Salesman

		annotation SummarizationSetBy = Automatic

	column Contact_Code
		dataType: string
		lineageTag: 1cd600fe-fd29-4aad-acf7-374e3e34c1db
		summarizeBy: none
		sourceColumn: Contact_Code

		annotation SummarizationSetBy = Automatic

	column AR_Acct
		dataType: int64
		formatString: 0
		lineageTag: 9303b753-f0e5-46bc-80c4-5032ab7a609f
		summarizeBy: sum
		sourceColumn: AR_Acct

		annotation SummarizationSetBy = Automatic

	column Customer
		dataType: string
		lineageTag: c64f2df9-a00e-40e2-b9cc-01adb9f56d84
		summarizeBy: none
		sourceColumn: Customer

		annotation SummarizationSetBy = Automatic

	column 'Order Count' =
			
			VAR _CurrentOrderNo = Parts_Open_Tickets[Order_No]
			RETURN
			COUNTROWS(FILTER(Parts_Open_Tickets, Parts_Open_Tickets[Order_No] =
			_CurrentOrderNo)
			)
		formatString: 0
		lineageTag: b8ddcbaf-b236-4c57-8d8b-857df5c24f38
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column $$_BackOrdered
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 679c8965-e9f6-4ce8-94b8-8c0e844ef7e6
		summarizeBy: sum
		sourceColumn: $$_BackOrdered

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'Order with BO Part' = IF([#_On_Back_Order] = 0, 0, 1)
		formatString: 0
		lineageTag: 1b4d2bef-c46e-4e8c-8a9f-48735003dc31
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Created_On
		dataType: dateTime
		formatString: Short Date
		lineageTag: 3c8c3def-ea29-449b-9e7b-a69ebd6506b5
		summarizeBy: none
		sourceColumn: Created_On

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Aging_Date_Source
		dataType: string
		lineageTag: 0e514712-1b12-473b-b3f3-1d17d80cb5d4
		summarizeBy: none
		sourceColumn: Aging_Date_Source

		annotation SummarizationSetBy = Automatic

	column $$_Available
		dataType: double
		lineageTag: dc3c432a-e111-4207-a978-f56a2181c1d2
		summarizeBy: sum
		sourceColumn: $$_Available

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Backorder_Pct
		dataType: double
		lineageTag: 2ec7a6ae-f08e-4ffa-aac1-f0ff1a856e22
		summarizeBy: sum
		sourceColumn: Backorder_Pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Aging Sort' =
			
			SWITCH(
			    TRUE(),
			    [Days_Open] >= 0 && [Days_Open] <= 7, 1,
			    [Days_Open] >= 8 && [Days_Open] <= 30, 2,
			    [Days_Open] >= 31 && [Days_Open] <= 60, 3,
			    [Days_Open] >= 61 && [Days_Open] <= 90, 4,
			    [Days_Open] > 90, 5,
			    6
			)
		formatString: 0
		lineageTag: 790f5296-b31e-4471-9bdd-96ce7bbfac1a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column WO_Creation_Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: a1f8f7fd-0bc4-411f-8517-30b1b57db719
		summarizeBy: none
		sourceColumn: WO_Creation_Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Aging_Sort_Order
		dataType: int64
		formatString: 0
		lineageTag: 23fd6277-c5ff-4e39-9c1d-6214b6cf6c11
		summarizeBy: sum
		sourceColumn: Aging_Sort_Order

		annotation SummarizationSetBy = Automatic

	partition Parts_Open_Tickets = m
		mode: import
		source =
				let
				    Source = Sql.Database("xcrafcusadsu3d3wi4anbgp6we-ch6iiwox4jveda3rmgudwi6hey.datawarehouse.fabric.microsoft.com", "LH_Parts_Reports_Data"),
				    dbo_Parts_Open_Tickets = Source{[Schema="dbo",Item="Parts_Open_Tickets"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(dbo_Parts_Open_Tickets, each ([Invoice_Type] <> "Invoice"))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

