table Fact_MDInvoices_NoFreight
	lineageTag: 863e2140-d95f-4a51-80a9-8302a9de7ae4

	column FileNumber
		dataType: int64
		formatString: 0
		lineageTag: b97d18f6-cf63-45d2-b946-398f47838049
		summarizeBy: none
		sourceColumn: FileNumber

		annotation SummarizationSetBy = User

	column LineNumber
		dataType: int64
		formatString: 0
		lineageTag: 458cbeb3-c379-4083-ad5a-0cb510ec842b
		summarizeBy: none
		sourceColumn: LineNumber

		annotation SummarizationSetBy = User

	column Branch
		dataType: string
		lineageTag: cb2a9eff-b633-40a4-80c4-94bc423af44b
		summarizeBy: none
		sourceColumn: Branch

		annotation SummarizationSetBy = Automatic

	column Franchise
		dataType: string
		lineageTag: 828d5326-6b03-45a7-bc1b-79d104fc9873
		summarizeBy: none
		sourceColumn: Franchise

		annotation SummarizationSetBy = Automatic

	column CustomerNumber
		dataType: string
		lineageTag: 6a39f993-f5f5-4d5c-8994-b3c1818369a7
		summarizeBy: none
		sourceColumn: CustomerNumber

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 66a1d87b-c922-4728-a992-4a166a7decb8
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CustomerOrderNumber
		dataType: string
		lineageTag: 73c2e4c8-6a4d-4eac-adea-2dcf9cea9dc4
		summarizeBy: none
		sourceColumn: CustomerOrderNumber

		annotation SummarizationSetBy = Automatic

	column RONumber
		dataType: int64
		formatString: 0
		lineageTag: 41587aa5-41db-41a9-84d8-964136cabc02
		summarizeBy: none
		sourceColumn: RONumber

		annotation SummarizationSetBy = User

	column PartNumber
		dataType: string
		lineageTag: e08c68ff-94a6-4fc9-823f-6ab5a8e1b5be
		summarizeBy: none
		sourceColumn: PartNumber

		annotation SummarizationSetBy = Automatic

	column OrderQty
		dataType: double
		lineageTag: ad27fbfb-eda9-47f3-954e-86a3b198aa2c
		summarizeBy: sum
		sourceColumn: OrderQty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UnitPrice
		dataType: double
		lineageTag: 51596918-34e5-4160-be8e-a3c475b17bc5
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UnitCost
		dataType: double
		lineageTag: 0467a26c-162f-490f-8195-95626363f581
		summarizeBy: sum
		sourceColumn: UnitCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LineTotal
		dataType: double
		lineageTag: 88745ae9-6aad-40f5-864b-8b6ed932428b
		summarizeBy: sum
		sourceColumn: LineTotal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Weight
		dataType: double
		lineageTag: ebac4efa-a530-468e-85cf-5972124d8cfc
		summarizeBy: sum
		sourceColumn: Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TotalLineWeight
		dataType: double
		lineageTag: 19a17ae9-ba32-4509-9c1c-c6013c3569ed
		summarizeBy: sum
		sourceColumn: TotalLineWeight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TotalFreightCharged
		dataType: double
		lineageTag: b6246452-e9f5-41dc-8efa-48983a65c0a2
		summarizeBy: sum
		sourceColumn: TotalFreightCharged

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FreightLineCount
		dataType: int64
		formatString: 0
		lineageTag: 869b8302-0b1a-42e8-9fff-f31bd76cb2bf
		summarizeBy: none
		sourceColumn: FreightLineCount

		annotation SummarizationSetBy = User

	column FreightStatus
		dataType: string
		lineageTag: a20b0b7e-a1ca-40e7-8fe3-1b391a51a49f
		summarizeBy: none
		sourceColumn: FreightStatus

		annotation SummarizationSetBy = Automatic

	column Salesperson
		dataType: string
		lineageTag: a8397c5c-af85-4eb6-8e08-5846ec4b3477
		summarizeBy: none
		sourceColumn: Salesperson

		annotation SummarizationSetBy = Automatic

	column JobCode
		dataType: string
		lineageTag: d4e51925-c66a-44b9-a766-a39c39896eeb
		summarizeBy: none
		sourceColumn: JobCode

		annotation SummarizationSetBy = Automatic

	column SuppliedQty
		dataType: double
		lineageTag: ef5d92aa-2329-470a-af9d-fc6b357c34c7
		summarizeBy: sum
		sourceColumn: SuppliedQty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BackorderQty
		dataType: double
		lineageTag: 6e66632f-343b-47c7-895f-1f5e2b7819d1
		summarizeBy: sum
		sourceColumn: BackorderQty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OrderType
		dataType: string
		lineageTag: 9fdb4203-4e2d-49b3-94d9-ca9ed2c038aa
		summarizeBy: none
		sourceColumn: OrderType

		annotation SummarizationSetBy = Automatic

	column MissedFreightAmount =
			VAR InvTotalWeight =
			    CALCULATE(
			        SUM(Fact_MDInvoices_NoFreight[TotalLineWeight]),
			        ALLEXCEPT(Fact_MDInvoices_NoFreight, Fact_MDInvoices_NoFreight[FileNumber])
			    )
			VAR ActualFreightAmt =
			    CALCULATE(
			        MAX(Fact_MDInvoices_NoFreight[TotalFreightCharged]),
			        ALLEXCEPT(Fact_MDInvoices_NoFreight, Fact_MDInvoices_NoFreight[FileNumber])
			    )
			VAR Bracket =
			    FILTER(
			        FreightCalculator,
			        FreightCalculator[PartWeightFrom] <= InvTotalWeight
			            && (FreightCalculator[PartWeightTo] + 1) > InvTotalWeight
			    )
			VAR BaseRate = MAXX(Bracket, FreightCalculator[BaseRate])
			VAR AdditiveRate = MAXX(Bracket, FreightCalculator[AdditiveRatePerPound])
			VAR BaseRateFinal = IF(ISBLANK(BaseRate), 0, BaseRate)
			VAR AdditiveRateFinal = IF(ISBLANK(AdditiveRate), 0.15, AdditiveRate)
			VAR CalcFreight = BaseRateFinal + (AdditiveRateFinal * InvTotalWeight)
			RETURN
			    CalcFreight - ActualFreightAmt
		formatString: $#,##0.00;($#,##0.00);$#,##0.00
		lineageTag: 8b3f2c91-5d4e-4a6b-9c1d-2e3f4a5b6c7d
		summarizeBy: none

		annotation SummarizationSetBy = User

	column PctFreightDifference =
			VAR InvTotalWeight =
			    CALCULATE(
			        SUM(Fact_MDInvoices_NoFreight[TotalLineWeight]),
			        ALLEXCEPT(Fact_MDInvoices_NoFreight, Fact_MDInvoices_NoFreight[FileNumber])
			    )
			VAR ActualFreightAmt =
			    CALCULATE(
			        MAX(Fact_MDInvoices_NoFreight[TotalFreightCharged]),
			        ALLEXCEPT(Fact_MDInvoices_NoFreight, Fact_MDInvoices_NoFreight[FileNumber])
			    )
			VAR Bracket =
			    FILTER(
			        FreightCalculator,
			        FreightCalculator[PartWeightFrom] <= InvTotalWeight
			            && (FreightCalculator[PartWeightTo] + 1) > InvTotalWeight
			    )
			VAR BaseRate = MAXX(Bracket, FreightCalculator[BaseRate])
			VAR AdditiveRate = MAXX(Bracket, FreightCalculator[AdditiveRatePerPound])
			VAR BaseRateFinal = IF(ISBLANK(BaseRate), 0, BaseRate)
			VAR AdditiveRateFinal = IF(ISBLANK(AdditiveRate), 0.15, AdditiveRate)
			VAR CalcFreight = BaseRateFinal + (AdditiveRateFinal * InvTotalWeight)
			VAR Diff = CalcFreight - ActualFreightAmt
			VAR AvgFreight = DIVIDE(CalcFreight + ActualFreightAmt, 2)
			RETURN
			    DIVIDE(Diff, AvgFreight)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 9c4f6b2a-8e3d-4f5a-1b6c-3d7e8f9a0b1c
		summarizeBy: none

		annotation SummarizationSetBy = User

	partition Fact_MDInvoices_NoFreight = m
		mode: import
		source =
				let
				    Source = Sql.Database("xcrafcusadsu3d3wi4anbgp6we-gxnyznhdptpenfw724g3o5sjzm.datawarehouse.fabric.microsoft.com", "LH_Master_Data"),
				    dbo_Fact_MDInvoices_NoFreight = Source{[Schema="dbo",Item="Fact_MDInvoices_NoFreight"]}[Data],
				    #"Extracted Date" = Table.TransformColumns(dbo_Fact_MDInvoices_NoFreight,{{"OrderDate", DateTime.Date, type date}})
				in
				    #"Extracted Date"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

