table Fact_PartsAdjustments
	lineageTag: 051c1486-913c-42cf-a061-6e8814e61c19

	column TransId
		dataType: int64
		formatString: 0
		lineageTag: 6119b1d5-2666-4e8a-92bd-de57bf0cbfa2
		summarizeBy: count
		sourceColumn: TransId

		annotation SummarizationSetBy = Automatic

	column RONumber
		dataType: string
		lineageTag: d3f4052b-c82f-49f5-9006-432bec5f40b4
		summarizeBy: none
		sourceColumn: RONumber

		annotation SummarizationSetBy = Automatic

	column TransDatetime
		dataType: dateTime
		formatString: Short Date
		lineageTag: fbcd9d40-0e75-43cb-9861-ab98fc3e9763
		summarizeBy: none
		sourceColumn: TransDatetime

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Branch
		dataType: string
		lineageTag: 206dfb15-149e-4285-a496-e81df85e53bb
		summarizeBy: none
		sourceColumn: Branch

		annotation SummarizationSetBy = Automatic

	column PartNumber
		dataType: string
		lineageTag: 98f26edb-46e9-4462-a6cb-19381e49b578
		summarizeBy: none
		sourceColumn: PartNumber

		annotation SummarizationSetBy = Automatic

	column PartDescription
		dataType: string
		lineageTag: 962c406e-a918-4b46-90d7-dd08754cfc4c
		summarizeBy: none
		sourceColumn: PartDescription

		annotation SummarizationSetBy = Automatic

	column Franchise
		dataType: string
		lineageTag: 1e8291b0-9ad8-4ee7-a337-6f2758b10aee
		summarizeBy: none
		sourceColumn: Franchise

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: d227349b-81a1-4b1a-b69c-e0039ca95aeb
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column Qty
		dataType: double
		formatString: 0
		lineageTag: 0cb09256-35e2-4b74-9e77-614e5191d9c9
		summarizeBy: sum
		sourceColumn: Qty

		annotation SummarizationSetBy = Automatic

	column CostValue
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 92a56865-6168-4d31-acca-02361504e194
		summarizeBy: sum
		sourceColumn: CostValue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column SellPrice1
		dataType: double
		lineageTag: c74c985e-b7e6-4226-a250-fa65915bd686
		summarizeBy: sum
		sourceColumn: SellPrice1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Salesman
		dataType: string
		lineageTag: 583f8edd-bfbc-41cf-8ad7-33084cbeb304
		summarizeBy: none
		sourceColumn: Salesman

		annotation SummarizationSetBy = Automatic

	column CustomerNo
		dataType: string
		lineageTag: 643440bf-64be-4eff-a317-30128218f5fb
		summarizeBy: none
		sourceColumn: CustomerNo

		annotation SummarizationSetBy = Automatic

	column Comments
		dataType: string
		lineageTag: c38b7188-3a8c-4bef-ae24-519a3cdc555f
		summarizeBy: none
		sourceColumn: Comments

		annotation SummarizationSetBy = Automatic

	column ModifiedDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 18bb7b90-fda4-4b78-ae17-45f005bc2a3d
		summarizeBy: none
		sourceColumn: ModifiedDate

		annotation SummarizationSetBy = Automatic

	column SubAccount
		dataType: int64
		formatString: 0
		lineageTag: 4f41fab9-a1be-47fe-ac7f-422e0b2b4fc0
		summarizeBy: sum
		sourceColumn: SubAccount

		annotation SummarizationSetBy = Automatic

	column GLTransDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 808cef57-9e9f-41f9-a5f1-618a578e3883
		summarizeBy: none
		sourceColumn: GLTransDate

		annotation SummarizationSetBy = Automatic

	column PAType
		dataType: string
		lineageTag: a3420d69-dd8a-47b0-9cd3-ecc14bcd3d7b
		summarizeBy: none
		sourceColumn: PAType

		annotation SummarizationSetBy = Automatic

	column PositiveQty
		dataType: double
		lineageTag: 8d50cf8c-7857-4f43-b8b0-5287554f3c9f
		summarizeBy: sum
		sourceColumn: PositiveQty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NegativeQty
		dataType: double
		lineageTag: c651f144-cf29-4c8b-ad50-c9602c96df11
		summarizeBy: sum
		sourceColumn: NegativeQty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PositiveCost
		dataType: double
		lineageTag: b7388efc-6859-49dd-9f5b-97ee15a5a5eb
		summarizeBy: sum
		sourceColumn: PositiveCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NegativeCost
		dataType: double
		lineageTag: 514bf70b-3002-4dde-8b08-9bb667062390
		summarizeBy: sum
		sourceColumn: NegativeCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column IsPositiveQty
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 4ccb4cb9-cdd5-4a1b-9a5c-28ad70dab34a
		summarizeBy: none
		sourceColumn: IsPositiveQty

		annotation SummarizationSetBy = Automatic

	column IsNegativeQty
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ed20ef9e-aa56-4e34-b567-94cfc29a8050
		summarizeBy: none
		sourceColumn: IsNegativeQty

		annotation SummarizationSetBy = Automatic

	column AbsQty
		dataType: double
		lineageTag: 425bce99-0524-4c10-b626-a9caad7434ff
		summarizeBy: sum
		sourceColumn: AbsQty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column AbsCost
		dataType: double
		lineageTag: 75fa25a5-93ad-42c4-9e87-bcd731818275
		summarizeBy: sum
		sourceColumn: AbsCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LoadedDatetime
		dataType: dateTime
		formatString: General Date
		lineageTag: 91ceb61a-19e0-4d67-a9f6-6f7383839a43
		summarizeBy: none
		sourceColumn: LoadedDatetime

		annotation SummarizationSetBy = Automatic

	partition Fact_PartsAdjustments = m
		mode: import
		source =
				let
				    Source = Sql.Database("xcrafcusadsu3d3wi4anbgp6we-gxnyznhdptpenfw724g3o5sjzm.datawarehouse.fabric.microsoft.com", "LH_Master_Data"),
				    dbo_Fact_PartsAdjustments = Source{[Schema="dbo",Item="Fact_PartsAdjustments"]}[Data],
				    #"Extracted Date" = Table.TransformColumns(dbo_Fact_PartsAdjustments,{{"TransDatetime", DateTime.Date, type date}})
				in
				    #"Extracted Date"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

