table Fact_AdjPairs_Summary
	lineageTag: 00b7269b-dbf2-4d2f-be7c-0d436a3b0ecd

	column NegTransId
		dataType: int64
		formatString: 0
		lineageTag: dd9699a3-3573-4ce3-9a33-0fbc1f174422
		summarizeBy: count
		sourceColumn: NegTransId

		annotation SummarizationSetBy = Automatic

	column NegRONumber
		dataType: string
		lineageTag: 76160c16-1851-473c-9819-0c0be0d794cb
		summarizeBy: none
		sourceColumn: NegRONumber

		annotation SummarizationSetBy = Automatic

	column NegDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: eb270f10-6500-4445-855e-292e69ff6a97
		summarizeBy: none
		sourceColumn: NegDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Branch
		dataType: string
		lineageTag: 2f99930e-b917-4ec6-995b-d020c6df20be
		summarizeBy: none
		sourceColumn: Branch

		annotation SummarizationSetBy = Automatic

	column PartNumber
		dataType: string
		lineageTag: 5ea58ed7-f790-4b0f-9093-c2eed85aff9e
		summarizeBy: none
		sourceColumn: PartNumber

		annotation SummarizationSetBy = Automatic

	column PartDescription
		dataType: string
		lineageTag: cfd0ec2e-38ad-4111-b553-f475130461e2
		summarizeBy: none
		sourceColumn: PartDescription

		annotation SummarizationSetBy = Automatic

	column NegQty
		dataType: double
		lineageTag: 7744e949-6813-4f59-b851-020d7a6e4800
		summarizeBy: sum
		sourceColumn: NegQty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NegAbsQty
		dataType: double
		lineageTag: 509841e7-4198-4a1b-8d62-cbc40a0e09f2
		summarizeBy: sum
		sourceColumn: NegAbsQty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NegCost
		dataType: double
		lineageTag: fdc595f3-b590-40c2-849a-23c0adf68fae
		summarizeBy: sum
		sourceColumn: NegCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NegAbsCost
		dataType: double
		lineageTag: dacc9f50-f5d8-4305-9e73-6d740cf1f0f9
		summarizeBy: sum
		sourceColumn: NegAbsCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NegPAType
		dataType: string
		lineageTag: c6110bde-3b4c-4354-b44a-a3a0f5a0e2d5
		summarizeBy: none
		sourceColumn: NegPAType

		annotation SummarizationSetBy = Automatic

	column PosMatchCount_12Mo
		dataType: double
		lineageTag: 7b2cebda-254b-4c34-944f-66d51600165a
		summarizeBy: sum
		sourceColumn: PosMatchCount_12Mo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PosTotalAbsQty_12Mo
		dataType: double
		lineageTag: cbc1190b-9205-4f6b-90ee-cc544c43b846
		summarizeBy: sum
		sourceColumn: PosTotalAbsQty_12Mo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PosTotalAbsCost_12Mo
		dataType: double
		lineageTag: f7d4f2c5-581a-42d8-bfa1-b1393c33c228
		summarizeBy: sum
		sourceColumn: PosTotalAbsCost_12Mo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PosMatchCount_24Mo
		dataType: double
		lineageTag: 39fc0388-afcd-4e4f-8b21-77f346a17c51
		summarizeBy: sum
		sourceColumn: PosMatchCount_24Mo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PosTotalAbsQty_24Mo
		dataType: double
		lineageTag: 3252ac2b-ed77-4cb5-8dc1-5f9bd8f0ff35
		summarizeBy: sum
		sourceColumn: PosTotalAbsQty_24Mo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PosTotalAbsCost_24Mo
		dataType: double
		lineageTag: a726a01f-102e-4e4c-af4b-1c3204da72c7
		summarizeBy: sum
		sourceColumn: PosTotalAbsCost_24Mo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column IsExact_12Mo
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 111251fa-c657-4c7c-8689-b8064a7bb599
		summarizeBy: none
		sourceColumn: IsExact_12Mo

		annotation SummarizationSetBy = Automatic

	column IsExact_24Mo
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 47160ba5-a53d-468b-aeaf-c770eb5e9a0f
		summarizeBy: none
		sourceColumn: IsExact_24Mo

		annotation SummarizationSetBy = Automatic

	column MatchType_12Mo
		dataType: string
		lineageTag: 4679bb12-d7b3-4323-9bba-83af8f19f7c6
		summarizeBy: none
		sourceColumn: MatchType_12Mo

		annotation SummarizationSetBy = Automatic

	column MatchType_24Mo
		dataType: string
		lineageTag: 948173e9-687b-4af1-aa13-020dab78d58b
		summarizeBy: none
		sourceColumn: MatchType_24Mo

		annotation SummarizationSetBy = Automatic

	column QtyRecoveryPct_12Mo
		dataType: double
		lineageTag: babe3e4c-bad6-4bff-8c90-4805cb29ecd8
		summarizeBy: sum
		sourceColumn: QtyRecoveryPct_12Mo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QtyRecoveryPct_24Mo
		dataType: double
		lineageTag: 7bd89fee-e001-4c9b-b082-9462d0d5990b
		summarizeBy: sum
		sourceColumn: QtyRecoveryPct_24Mo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LoadedDatetime
		dataType: dateTime
		formatString: General Date
		lineageTag: 53271883-dcfe-46b4-b3ae-082c88274f9a
		summarizeBy: none
		sourceColumn: LoadedDatetime

		annotation SummarizationSetBy = Automatic

	partition Fact_AdjPairs_Summary = m
		mode: import
		source =
				let
				    Source = Sql.Database("xcrafcusadsu3d3wi4anbgp6we-gxnyznhdptpenfw724g3o5sjzm.datawarehouse.fabric.microsoft.com", "LH_Master_Data"),
				    dbo_Fact_AdjPairs_Summary = Source{[Schema="dbo",Item="Fact_AdjPairs_Summary"]}[Data],
				    #"Extracted Date" = Table.TransformColumns(dbo_Fact_AdjPairs_Summary,{{"NegDate", DateTime.Date, type date}})
				in
				    #"Extracted Date"

