table armaster
	lineageTag: 0da41f12-3be7-4f64-b9f2-725d5e37b1da

	column AccountNumber
		dataType: string
		lineageTag: 65de2f8a-773f-448c-970c-4edf96de077e
		summarizeBy: none
		sourceColumn: AccountNumber

		annotation SummarizationSetBy = Automatic

	column ContactID
		dataType: string
		lineageTag: 2cd92c2d-0895-4f0f-a731-d395f247f0a8
		summarizeBy: none
		sourceColumn: ContactID

		annotation SummarizationSetBy = Automatic

	column CreditLimit
		dataType: double
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: 5d04f87d-a31c-4c0b-9a32-0f1de495d232
		summarizeBy: sum
		sourceColumn: CreditLimit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column AccountBalance
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 846740d2-e2ad-4998-adec-8322cb018304
		summarizeBy: sum
		sourceColumn: AccountBalance

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Aging30
		dataType: double
		lineageTag: 9fdcec6b-4170-43bc-a9a8-e46075e79d7e
		summarizeBy: sum
		sourceColumn: Aging30

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Aging60
		dataType: double
		lineageTag: 5a9efa52-e7d7-4038-8bff-32895ee58403
		summarizeBy: sum
		sourceColumn: Aging60

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Aging90
		dataType: double
		lineageTag: 307df460-d9d2-428c-9044-d3ea1d18f7c0
		summarizeBy: sum
		sourceColumn: Aging90

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LastPaymentDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 8d06e78c-a360-445d-a85e-6ab40ba6fd12
		summarizeBy: none
		sourceColumn: LastPaymentDate

		annotation SummarizationSetBy = Automatic

	column LastPaymentAmount
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 3b7d024b-eedb-4156-9d60-97298765286e
		summarizeBy: sum
		sourceColumn: LastPaymentAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column StatementType
		dataType: string
		lineageTag: a7dec1ec-b9c4-4094-942b-558dab4f8fea
		summarizeBy: none
		sourceColumn: StatementType

		annotation SummarizationSetBy = Automatic

	column CreditTerm
		dataType: string
		lineageTag: 9c17f6b5-940e-4850-937e-8e58a30db96f
		summarizeBy: none
		sourceColumn: CreditTerm

		annotation SummarizationSetBy = Automatic

	column PaymentMethod
		dataType: string
		lineageTag: 8eb9b905-3904-4989-9f2d-85da6aacf26e
		summarizeBy: none
		sourceColumn: PaymentMethod

		annotation SummarizationSetBy = Automatic

	column ModifiedDate
		dataType: dateTime
		formatString: General Date
		lineageTag: cde9586c-ee3a-420e-903d-ed2f4b606fa2
		summarizeBy: none
		sourceColumn: ModifiedDate

		annotation SummarizationSetBy = Automatic

	column Aging120
		dataType: double
		lineageTag: 5d887dce-7b28-439c-952b-d00e6494cd80
		summarizeBy: sum
		sourceColumn: Aging120

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column YTDCredits
		dataType: double
		lineageTag: 0958e034-b37b-4c31-9b5a-16796d176c13
		summarizeBy: sum
		sourceColumn: YTDCredits

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column YTDDebits
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: bbd4c1b0-cdfa-4dce-87e5-7d8ec15c507d
		summarizeBy: sum
		sourceColumn: YTDDebits

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column LYTDCredits
		dataType: double
		lineageTag: 315e83aa-cc2a-4f76-b410-a2138a56b4b9
		summarizeBy: sum
		sourceColumn: LYTDCredits

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LYTDDebits
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 6e4a36fa-9c42-4295-b1a5-3b234fe03ed1
		summarizeBy: sum
		sourceColumn: LYTDDebits

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Type
		dataType: string
		lineageTag: d256be9f-6d30-40e3-acf8-4f8c33e2b700
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column CreationDate
		dataType: dateTime
		formatString: General Date
		lineageTag: fe88de6a-e001-4a2b-b002-1ddc37c26792
		summarizeBy: none
		sourceColumn: CreationDate

		annotation SummarizationSetBy = Automatic

	partition armaster = m
		mode: import
		source =
				let
				    Source = Sql.Database("xcrafcusadsu3d3wi4anbgp6we-gxnyznhdptpenfw724g3o5sjzm.datawarehouse.fabric.microsoft.com", "LH_Master_Data"),
				    dbo_armaster = Source{[Schema="dbo",Item="armaster"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dbo_armaster,{{"AccountNumber", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

