table TechnicianAttendance
	lineageTag: e0b7b6dd-b4f2-470a-a791-a3a583e97ac1

	column Branch
		dataType: string
		lineageTag: 11ea5cc3-7723-48e1-b2ab-5c90b4170716
		summarizeBy: none
		sourceColumn: Branch

		annotation SummarizationSetBy = Automatic

	column TechnicianCode
		dataType: string
		lineageTag: 7eaa25c2-4e8a-4ed0-b644-f793b19c5d67
		summarizeBy: none
		sourceColumn: TechnicianCode

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: ceda352f-8962-4e0c-ae2d-f82b1b8b2b98
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 860db3b5-3c6b-4a27-8bda-d754aed0eca3
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Hours
		dataType: double
		lineageTag: 5e54463b-6687-4287-88ae-4ba50a8ccbbc
		summarizeBy: sum
		sourceColumn: Hours

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0a1ca0fb-577a-4129-a1f9-f4c90857f100
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition TechnicianAttendance = m
		mode: import
		source =
				let
				    Source = Sql.Database("xcrafcusadsu3d3wi4anbgp6we-wczpfb6a52fude7azc6zsgeuty.datawarehouse.fabric.microsoft.com", "LH_Service_Reports_Data"),
				    dbo_TechnicianAttendance = Source{[Schema="dbo",Item="TechnicianAttendance"]}[Data],
				    #"Added Custom" = Table.AddColumn(dbo_TechnicianAttendance, "dDateCustom", each #date([Year], [Month], 1)),
				    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"dDateCustom", type date}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"dDateCustom", "Date"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

