table jdis_Phy_Inv
	lineageTag: 0e2dfaaa-d8e3-4387-9391-49bcf6e65cec

	column Branch
		dataType: string
		lineageTag: fe43a3ee-ad1f-4f4b-b627-1a34bdb3fbb0
		summarizeBy: none
		sourceColumn: Branch

		annotation SummarizationSetBy = Automatic

	column Franchise
		dataType: string
		lineageTag: 4875a241-6596-42fc-ae2b-fd3a2646de12
		summarizeBy: none
		sourceColumn: Franchise

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: a0486d29-23bf-4b0f-828c-863fbe2b62c8
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column Bin
		dataType: string
		lineageTag: 1d205873-5e1b-4969-9ae2-0b838b38a38b
		summarizeBy: none
		sourceColumn: Bin

		annotation SummarizationSetBy = Automatic

	column Combined
		dataType: string
		lineageTag: 93a1cd4c-fbf2-4ad0-8014-bf1f9bc393f3
		summarizeBy: none
		sourceColumn: Combined

		annotation SummarizationSetBy = Automatic

	column 'Part No'
		dataType: string
		lineageTag: 0ed6b74b-7f2b-433c-92d8-8d07473fa57a
		summarizeBy: none
		sourceColumn: Part No

		annotation SummarizationSetBy = Automatic

	column 'Bin Qty'
		dataType: double
		formatString: 0
		lineageTag: 15faec80-bb74-40cf-bc76-5fb1510f9c3e
		summarizeBy: sum
		sourceColumn: Bin Qty

		annotation SummarizationSetBy = Automatic

	column 'On Hand Qty'
		dataType: double
		lineageTag: cbe87735-495e-4bf2-8873-d17e9b381f36
		summarizeBy: sum
		sourceColumn: On Hand Qty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Bulk Bin Qty'
		dataType: double
		lineageTag: 6b6178cd-ed7c-4aa2-91ae-d80e899a166b
		summarizeBy: sum
		sourceColumn: Bulk Bin Qty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Stocktake Date'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 81fbc424-d48e-4b2d-abc4-d45b1de81f0a
		summarizeBy: none
		sourceColumn: Stocktake Date

		variation Variation
			isDefault
			relationship: 335c8ed2-6683-48eb-81a6-4299e64a1785
			defaultHierarchy: LocalDateTable_b5b3ed34-09cb-4447-b972-044482ece3f9.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Date Created'
		dataType: dateTime
		formatString: Short Date
		lineageTag: ab8d150f-972e-482f-8091-85f0172ecfc5
		summarizeBy: none
		sourceColumn: Date Created

		variation Variation
			isDefault
			relationship: a4bd32e0-01b3-4da0-9ee7-941eb6a398a3
			defaultHierarchy: LocalDateTable_cc551eda-c6f7-466e-9193-f2f6f0df0e7b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Is Bin Counted'
		dataType: int64
		formatString: 0
		lineageTag: 1bb09588-1c70-42de-a049-7e3d2a43849c
		summarizeBy: sum
		sourceColumn: Is Bin Counted

		annotation SummarizationSetBy = Automatic

	column 'Is Part Counted'
		dataType: int64
		formatString: 0
		lineageTag: f452905c-2081-4823-896f-2d16ef10832f
		summarizeBy: sum
		sourceColumn: Is Part Counted

		annotation SummarizationSetBy = Automatic

	column 'Has Bin Qty'
		dataType: int64
		formatString: 0
		lineageTag: e0975c56-8eb3-401e-9901-47919de5c893
		summarizeBy: sum
		sourceColumn: Has Bin Qty

		annotation SummarizationSetBy = Automatic

	column 'Is Part with Qty Counted'
		dataType: int64
		formatString: 0
		lineageTag: d3523b7f-109b-41e3-a058-cca4ff69330e
		summarizeBy: sum
		sourceColumn: Is Part with Qty Counted

		annotation SummarizationSetBy = Automatic

	column 'Bin Qty Counted'
		dataType: int64
		formatString: 0
		lineageTag: ff6c3d67-8b98-4f2d-b0ed-35e0ee88ebb2
		summarizeBy: sum
		sourceColumn: Bin Qty Counted

		annotation SummarizationSetBy = Automatic

	column 'Bin-Part No'
		dataType: string
		lineageTag: 405be50d-d9ef-4380-b902-519ebb3e6b61
		summarizeBy: none
		sourceColumn: Bin-Part No

		annotation SummarizationSetBy = Automatic

	column 'Has Qty Variance'
		dataType: int64
		formatString: 0
		lineageTag: 01e80b7e-223d-405f-8819-2c975fbb85b2
		summarizeBy: sum
		sourceColumn: Has Qty Variance

		annotation SummarizationSetBy = Automatic

	column 'Last Activity Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: df94a8d4-0e25-4888-99bd-3720b5048327
		summarizeBy: none
		sourceColumn: Last Activity Date

		variation Variation
			isDefault
			relationship: ceb0b27e-b0a9-4936-ad92-48faffe0b48b
			defaultHierarchy: LocalDateTable_96976973-4080-4cd3-93b1-c235fa1a1f90.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Days Since Last Activity'
		dataType: int64
		formatString: 0
		lineageTag: 641294d2-a69f-4a43-8f8f-1b42522683df
		summarizeBy: sum
		sourceColumn: Days Since Last Activity

		annotation SummarizationSetBy = Automatic

	partition jdis_Phy_Inv = m
		mode: import
		source =
				let
				    Source = Sql.Database("xcrafcusadsu3d3wi4anbgp6we-ch6iiwox4jveda3rmgudwi6hey.datawarehouse.fabric.microsoft.com", "LH_Parts_Reports_Data"),
				    dbo_jdis_Phy_Inv = Source{[Schema="dbo",Item="jdis_Phy_Inv"]}[Data],
				    #"Replaced Value" = Table.ReplaceValue(dbo_jdis_Phy_Inv,"d","D",Replacer.ReplaceText,{"Franchise"}),
				    #"Filtered Rows" = Table.SelectRows(#"Replaced Value", each ([Bin] <> "        "))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

