table Parts_Low_Margin_jdis_InMaster
	lineageTag: 037947ce-7ad8-4171-9595-f474828f11b7

	column Branch
		dataType: string
		lineageTag: 3e50def8-c5c4-4a2c-b9f2-a2ba80d229d1
		summarizeBy: none
		sourceColumn: Branch

		annotation SummarizationSetBy = Automatic

	column Franchise
		dataType: string
		lineageTag: f60d1d90-e4e7-471f-a03b-264c85667eff
		summarizeBy: none
		sourceColumn: Franchise

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 6c7c4c5e-7467-42ee-9def-5b51a06d3862
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column Bin
		dataType: string
		lineageTag: 63960ee5-2a97-4f91-a5ca-3b04f5f01f3a
		summarizeBy: none
		sourceColumn: Bin

		annotation SummarizationSetBy = Automatic

	column Cost
		dataType: double
		lineageTag: 45151782-a897-4b77-ad07-c658cce2519f
		summarizeBy: sum
		sourceColumn: Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column user_field_3
		dataType: string
		lineageTag: e128556c-37eb-40d0-b02d-7541f50fb832
		summarizeBy: none
		sourceColumn: user_field_3

		annotation SummarizationSetBy = Automatic

	column STK_ORDER_PRICE
		dataType: double
		lineageTag: 2ec3e600-8310-492f-867e-8d163f307fbe
		summarizeBy: sum
		sourceColumn: STK_ORDER_PRICE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Part No'
		dataType: string
		lineageTag: 2344295b-bdd5-4483-82e1-17e466d16190
		summarizeBy: none
		sourceColumn: Part No

		annotation SummarizationSetBy = Automatic

	column 'Bin Qty'
		dataType: double
		lineageTag: 7a049785-3591-4d3b-8f00-458f1797ec62
		summarizeBy: sum
		sourceColumn: Bin Qty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Bulk Bin'
		dataType: string
		lineageTag: 5a6ce58d-c373-414d-a785-36b6189c2474
		summarizeBy: none
		sourceColumn: Bulk Bin

		annotation SummarizationSetBy = Automatic

	column 'Bulk Bin Qty'
		dataType: double
		lineageTag: 0c2227c3-c879-403c-ae1d-2034d9ec962b
		summarizeBy: sum
		sourceColumn: Bulk Bin Qty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'On Hand Qty'
		dataType: double
		lineageTag: 83c85a29-c190-44c4-8586-8eee4238dae6
		summarizeBy: sum
		sourceColumn: On Hand Qty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Pending Qty'
		dataType: double
		lineageTag: 62c09f31-f720-4568-8883-819701fdd702
		summarizeBy: sum
		sourceColumn: Pending Qty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Date Last Requested'
		dataType: dateTime
		formatString: General Date
		lineageTag: 72f47206-e853-47e1-a958-447b6557fabc
		summarizeBy: none
		sourceColumn: Date Last Requested

		variation Variation
			isDefault
			relationship: 4441f745-2e82-4024-a86a-e8450058b9fc
			defaultHierarchy: LocalDateTable_c92e6afb-2011-45c1-aa80-1f20ef42382c.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Stock Take Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 6629d9a7-e9ff-432e-8a00-ed526512cb21
		summarizeBy: none
		sourceColumn: Stock Take Date

		variation Variation
			isDefault
			relationship: 6d6a4840-920c-4e9e-bb9e-1766b20896d2
			defaultHierarchy: LocalDateTable_0d258976-f40e-4bd7-8b8d-a1257cb779db.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'List Price Manuf'
		dataType: double
		lineageTag: e0e64409-440a-4ecd-84be-0c53b070fefb
		summarizeBy: sum
		sourceColumn: List Price Manuf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'List Price'
		dataType: double
		lineageTag: ae6fdb0b-93dd-485f-801b-3c3ac92fad89
		summarizeBy: sum
		sourceColumn: List Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Inventory Cost'
		dataType: double
		lineageTag: 4d68116f-d7c0-4168-9c64-9bad918295a3
		summarizeBy: sum
		sourceColumn: Inventory Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Sell Price'
		dataType: double
		lineageTag: a6938d07-70da-47b5-b5b9-7f19e839f399
		summarizeBy: sum
		sourceColumn: Sell Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Parts_Low_Margin_jdis_InMaster = m
		mode: import
		source =
				let
				    Source = Sql.Database("xcrafcusadsu3d3wi4anbgp6we-ch6iiwox4jveda3rmgudwi6hey.datawarehouse.fabric.microsoft.com", "LH_Parts_Reports_Data"),
				    dbo_Parts_Low_Margin_jdis_InMaster = Source{[Schema="dbo",Item="Parts_Low_Margin_jdis_InMaster"]}[Data],
				    #"Replaced Value" = Table.ReplaceValue(dbo_Parts_Low_Margin_jdis_InMaster,"d","D",Replacer.ReplaceText,{"Franchise"})
				in
				    #"Replaced Value"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

