table Parts_Open_Tickets_Details
	lineageTag: 4aa71bdc-d3d0-4bc4-a1c1-f4695863fa78

	column Location
		dataType: string
		lineageTag: 52c552f7-ea54-4c94-96a5-29dde5be9226
		summarizeBy: none
		sourceColumn: Location

		annotation SummarizationSetBy = Automatic

	column Order_No
		dataType: int64
		formatString: 0
		lineageTag: d0a8a3dd-5d89-4999-ade0-4ff762bea192
		summarizeBy: none
		sourceColumn: Order_No

		annotation SummarizationSetBy = Automatic

	column RO_Number
		dataType: int64
		formatString: 0
		lineageTag: 27e05493-acd1-4b0a-b82c-441bd1935bb5
		summarizeBy: sum
		sourceColumn: RO_Number

		annotation SummarizationSetBy = Automatic

	column Order_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4a243fe4-d003-440a-be0b-392f31c4df30
		summarizeBy: none
		sourceColumn: Order_Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Days_Open
		dataType: int64
		formatString: 0
		lineageTag: 59c3df9c-c9b4-42fc-a7fe-d23b2ef1c41e
		summarizeBy: sum
		sourceColumn: Days_Open

		annotation SummarizationSetBy = Automatic

	column Part_No
		dataType: string
		lineageTag: 5947b153-5fc8-460f-b6eb-c06774f74ac6
		summarizeBy: none
		sourceColumn: Part_No

		annotation SummarizationSetBy = Automatic

	column Quantity_Ordered
		dataType: double
		formatString: 0
		lineageTag: 0b603b63-09a5-4466-9d40-01b9d7258931
		summarizeBy: sum
		sourceColumn: Quantity_Ordered

		annotation SummarizationSetBy = Automatic

	column Unit_Price
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: a8c6bc2a-91f6-4ce8-a9c3-b044ae41941d
		summarizeBy: sum
		sourceColumn: Unit_Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column Line_Total
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 67226e56-bc9c-4f21-8b75-032544d01573
		summarizeBy: sum
		sourceColumn: Line_Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column BackOrdered_QTY
		dataType: double
		formatString: 0
		lineageTag: e79c7f42-8f75-4654-9057-d61070a0d86d
		summarizeBy: sum
		sourceColumn: BackOrdered_QTY

		annotation SummarizationSetBy = Automatic

	column 'BackOrdered Flag' =
			IF(
			    [BackOrdered_QTY] = 0, 0, 1)
		formatString: 0
		lineageTag: ea1175e3-6c5b-414c-a1a5-a898fb4a79a1
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column Created_On
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6d5c90d1-c041-4e30-bec0-22238d6e69b6
		summarizeBy: none
		sourceColumn: Created_On

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Location_Name
		dataType: string
		lineageTag: 10f5b15c-faf8-4ad1-b092-08e74335f8c2
		summarizeBy: none
		sourceColumn: Location_Name

		annotation SummarizationSetBy = Automatic

	column File_No
		dataType: int64
		formatString: 0
		lineageTag: 395efeb9-b243-4e2d-94a0-a27cc31bff8e
		summarizeBy: sum
		sourceColumn: File_No

		annotation SummarizationSetBy = Automatic

	column Invoice_Type
		dataType: string
		lineageTag: 67b6f9d1-ab75-4931-acce-428f01b49b16
		summarizeBy: none
		sourceColumn: Invoice_Type

		annotation SummarizationSetBy = Automatic

	column Aging
		dataType: string
		lineageTag: 3519d76d-99ad-448d-9710-dd0c8de48d99
		summarizeBy: none
		sourceColumn: Aging

		annotation SummarizationSetBy = Automatic

	column Aging_Date_Source
		dataType: string
		lineageTag: 888ab10f-508c-4107-885a-b03e117d1b72
		summarizeBy: none
		sourceColumn: Aging_Date_Source

		annotation SummarizationSetBy = Automatic

	column Available_QTY
		dataType: double
		lineageTag: b9f13285-8e6a-44d9-a033-abda748c70ee
		summarizeBy: sum
		sourceColumn: Available_QTY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Line_Backorder_Pct
		dataType: double
		lineageTag: 9408812d-a6d2-4d79-b0d7-1f72c51d80f6
		summarizeBy: sum
		sourceColumn: Line_Backorder_Pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Contact_Code
		dataType: string
		lineageTag: 54b5b49d-2481-44b3-96db-7ef6875ab269
		summarizeBy: none
		sourceColumn: Contact_Code

		annotation SummarizationSetBy = Automatic

	column Customer
		dataType: string
		lineageTag: 7b021dd8-2cd9-4c57-816c-2202c15ac553
		summarizeBy: none
		sourceColumn: Customer

		annotation SummarizationSetBy = Automatic

	column Salesman
		dataType: string
		lineageTag: 110af6ee-3f33-47ce-8514-2890354bb16f
		summarizeBy: none
		sourceColumn: Salesman

		annotation SummarizationSetBy = Automatic

	column WO_Creation_Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4c95705d-e398-4df1-ad97-fff70e4dca5a
		summarizeBy: none
		sourceColumn: WO_Creation_Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Aging_Sort_Order
		dataType: int64
		formatString: 0
		lineageTag: 4b3a51b0-553d-44ac-8136-ac65782a14d8
		summarizeBy: sum
		sourceColumn: Aging_Sort_Order

		annotation SummarizationSetBy = Automatic

	partition Parts_Open_Tickets_Details = m
		mode: import
		source =
				let
				    Source = Sql.Database("xcrafcusadsu3d3wi4anbgp6we-ch6iiwox4jveda3rmgudwi6hey.datawarehouse.fabric.microsoft.com", "LH_Parts_Reports_Data"),
				    dbo_Parts_Open_Tickets_Details = Source{[Schema="dbo",Item="Parts_Open_Tickets_Details"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(dbo_Parts_Open_Tickets_Details, each ([Invoice_Type] <> "Invoice"))
				in
				    #"Filtered Rows"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

