table 'Inspection Goals'
	lineageTag: 1ae08b2b-585b-4e6b-b27b-168a66b26d9a

	column LOCATION
		dataType: string
		lineageTag: a30125b9-0723-4055-a2c2-bee095f2a3eb
		summarizeBy: none
		sourceColumn: LOCATION

		annotation SummarizationSetBy = Automatic

	column '2025 Inspections Goal'
		dataType: double
		formatString: 0
		lineageTag: a5efb640-7858-4652-9834-ffc42214aeac
		summarizeBy: sum
		sourceColumn: 2025 Inspections Goal

		annotation SummarizationSetBy = Automatic

	column '2025 Labor $$ w/ Inspection Goal'
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 55013ef4-0952-46b0-bdb8-d38ee7ae78e1
		summarizeBy: sum
		sourceColumn: 2025 Labor $$ w/ Inspection Goal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column '2025 Total Parts $$ Goal'
		dataType: double
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 710de3ca-82c9-4ddf-b3fb-f45203e6e944
		summarizeBy: sum
		sourceColumn: 2025 Total Parts $$ Goal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column '2025 CS690/770 Inspections Goal'
		dataType: int64
		formatString: 0
		lineageTag: 3de7e97f-03bb-4deb-a051-72f4e0811b4d
		summarizeBy: sum
		sourceColumn: 2025 CS690/770 Inspections Goal

		annotation SummarizationSetBy = Automatic

	column '2025 CS690/770 Labor $$ w/ Inspection Goal'
		dataType: double
		lineageTag: 0db19c18-b108-49af-b522-36cb96b3590e
		summarizeBy: sum
		sourceColumn: 2025 CS690/770 Labor $$ w/ Inspection Goal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '2025 CS690/770 Total Parts $$ Goal'
		dataType: double
		lineageTag: 1a8d5f46-d3a1-4ba4-900a-66f6993acab1
		summarizeBy: sum
		sourceColumn: 2025 CS690/770 Total Parts $$ Goal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Inspection Goals' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://spitractor-my.sharepoint.com/personal/bfox_spitractor_com/Documents/Power%20BI%20-%20Vis/Data/Inspection%20Goals.xlsx"), null, true),
				    Table3_Table = Source{[Item="Table3",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Table3_Table,{{"LOCATION", type any}, {"2025 Inspections Goal", type number}, {"2025 Labor $$ w/ Inspection Goal", type number}, {"2025 Total Parts $$ Goal", type number}, {"2025 CS690/770 Inspections Goal", Int64.Type}, {"2025 CS690/770 Labor $$ w/ Inspection Goal", type number}, {"2025 CS690/770 Total Parts $$ Goal", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

