table 'Data Refresh'
	lineageTag: 1f2b1b6f-72f6-457c-8b72-e853490f2579

	column CurrentDateTime
		dataType: dateTime
		formatString: General Date
		lineageTag: 204b15fe-3bd6-4440-bee3-fcb1006e36c5
		summarizeBy: none
		sourceColumn: CurrentDateTime

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: a630e4c0-21d6-4a16-8b6c-e8a003ef1783
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 80683217-67b3-4735-84f4-8870bcd8b144
		summarizeBy: none
		sourceColumn: Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	partition 'Data Refresh' = m
		mode: import
		source =
				let
				    // Fabric/Power BI Service runs in UTC - DateTime.LocalNow() returns UTC, not local time.
				    // DateTimeZone.SwitchZone converts UTC to Central Time with automatic DST handling.
				    UtcNow    = DateTimeZone.UtcNow(),
				    UtcDT     = DateTimeZone.RemoveZone(UtcNow),
				    CurYear   = Date.Year(DateTime.Date(UtcDT)),
				    Mar1      = #date(CurYear, 3, 1),
				    Sun1Mar   = Date.AddDays(Mar1, Number.Mod(7 - Date.DayOfWeek(Mar1, Day.Sunday), 7)),
				    DstStart  = #datetime(CurYear, 3, Date.Day(Date.AddDays(Sun1Mar, 7)), 8, 0, 0),
				    Nov1      = #date(CurYear, 11, 1),
				    Sun1Nov   = Date.AddDays(Nov1, Number.Mod(7 - Date.DayOfWeek(Nov1, Day.Sunday), 7)),
				    DstEnd    = #datetime(CurYear, 11, Date.Day(Sun1Nov), 7, 0, 0),
				    OffsetHrs = if UtcDT >= DstStart and UtcDT < DstEnd then -5 else -6,
				    LocalDT   = DateTimeZone.RemoveZone(DateTimeZone.SwitchZone(UtcNow, OffsetHrs, 0)),
				    Source    = #table({"CurrentDateTime"}, {{LocalDT}}),
				    AddDate   = Table.DuplicateColumn(Source, "CurrentDateTime", "Date"),
				    AddTime   = Table.DuplicateColumn(AddDate, "Date", "Time"),
				    ChgTypes  = Table.TransformColumnTypes(AddTime, {{"Date", type date}, {"Time", type time}})
				in
				    ChgTypes

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

