table 'Data Refresh'
	lineageTag: 44cb2378-b83a-4d05-8733-930c10a2f53a

	column CurrentDateTime
		dataType: string
		lineageTag: bfb2192b-cd4e-4a0e-94f3-0b0775eba255
		summarizeBy: none
		sourceColumn: CurrentDateTime

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 28756715-8499-4a7e-877e-6b9105faf1d6
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 5e7faf39-b227-4cf4-8adc-ebbc3f66b58c
		summarizeBy: none
		sourceColumn: Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	partition 'Data Refresh' = m
		mode: import
		source =
				let
				    // Fabric/Power BI Service runs in UTC - DateTime.LocalNow() returns UTC, not local time.
				    // DateTimeZone.SwitchZone converts UTC to Central Time with automatic DST handling.
				    UtcNow    = DateTimeZone.UtcNow(),
				    UtcDT     = DateTimeZone.RemoveZone(UtcNow),
				    CurYear   = Date.Year(DateTime.Date(UtcDT)),
				    Mar1      = #date(CurYear, 3, 1),
				    Sun1Mar   = Date.AddDays(Mar1, Number.Mod(7 - Date.DayOfWeek(Mar1, Day.Sunday), 7)),
				    DstStart  = #datetime(CurYear, 3, Date.Day(Date.AddDays(Sun1Mar, 7)), 8, 0, 0),
				    Nov1      = #date(CurYear, 11, 1),
				    Sun1Nov   = Date.AddDays(Nov1, Number.Mod(7 - Date.DayOfWeek(Nov1, Day.Sunday), 7)),
				    DstEnd    = #datetime(CurYear, 11, Date.Day(Sun1Nov), 7, 0, 0),
				    OffsetHrs = if UtcDT >= DstStart and UtcDT < DstEnd then -5 else -6,
				    LocalDT   = DateTimeZone.RemoveZone(DateTimeZone.SwitchZone(UtcNow, OffsetHrs, 0)),
				    Source    = #table({"CurrentDateTime"}, {{LocalDT}}),
				    AddDate   = Table.DuplicateColumn(Source, "CurrentDateTime", "Date"),
				    AddTime   = Table.DuplicateColumn(AddDate, "Date", "Time"),
				    ChgTypes  = Table.TransformColumnTypes(AddTime, {{"Date", type date}, {"Time", type time}})
				in
				    ChgTypes

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

