table 'Data Refresh'
	lineageTag: 44cb2378-b83a-4d05-8733-930c10a2f53a

	column CurrentDateTime
		dataType: dateTime
		formatString: General Date
		lineageTag: bfb2192b-cd4e-4a0e-94f3-0b0775eba255
		summarizeBy: none
		sourceColumn: CurrentDateTime

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 28756715-8499-4a7e-877e-6b9105faf1d6
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 5e7faf39-b227-4cf4-8adc-ebbc3f66b58c
		summarizeBy: none
		sourceColumn: Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	partition 'Data Refresh' = m
		mode: import
		source =
				let
				    Source = #table({"CurrentDateTime"}, {{DateTime.LocalNow() - #duration(0,6,0,0)}}),
				    #"Duplicated Column" = Table.DuplicateColumn(Source, "CurrentDateTime", "CurrentDateTime - Copy"),
				    #"Duplicated Column1" = Table.DuplicateColumn(#"Duplicated Column", "CurrentDateTime", "CurrentDateTime - Copy.1"),
				    #"Renamed Columns" = Table.RenameColumns(#"Duplicated Column1",{{"CurrentDateTime - Copy", "Date"}, {"CurrentDateTime - Copy.1", "Time"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Date", type date}, {"Time", type time}, {"CurrentDateTime", type datetime}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

