table Fact_Part_Transactions
	lineageTag: 19d9984f-93ca-43c8-948b-74d3645ccf43

	column TransactionDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 8d29db38-f289-4d7f-9beb-5941dde2be2d
		summarizeBy: none
		sourceColumn: TransactionDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FranchiseKey
		dataType: int64
		formatString: 0
		lineageTag: ee48c933-3138-4af3-853f-3ce0e9f1ac00
		summarizeBy: none
		sourceColumn: FranchiseKey

		annotation SummarizationSetBy = Automatic

	column PartNumberKey
		dataType: int64
		formatString: 0
		lineageTag: 15a01670-83b5-4a84-93bf-f721e06d8f7d
		summarizeBy: none
		sourceColumn: PartNumberKey

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: double
		lineageTag: fd0bc0d9-e418-4206-a1ee-ed2347c3a88d
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SaleAmount
		dataType: double
		lineageTag: 4f68eca5-babf-4ddb-a059-b0d8bfb86a73
		summarizeBy: sum
		sourceColumn: SaleAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CostAmount
		dataType: double
		lineageTag: 4328178f-284a-4e50-ae50-7c86b03adb11
		summarizeBy: sum
		sourceColumn: CostAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BranchKey
		dataType: int64
		formatString: 0
		lineageTag: b2feb9dc-7645-4c9d-bd42-0e5d04c4f4e0
		summarizeBy: count
		sourceColumn: BranchKey

		annotation SummarizationSetBy = Automatic

	column Branch
		dataType: string
		lineageTag: 6d1fc259-cb67-4697-b16a-4d3edd3cafc6
		summarizeBy: none
		sourceColumn: Branch

		annotation SummarizationSetBy = Automatic

	partition Fact_Part_Transactions = m
		mode: import
		source =
				let
				    Source = Sql.Database("xcrafcusadsu3d3wi4anbgp6we-gxnyznhdptpenfw724g3o5sjzm.datawarehouse.fabric.microsoft.com", "LH_Master_Data"),
				    dbo_Fact_Part_Transactions = Source{[Schema="dbo",Item="Fact_Part_Transactions"]}[Data],
				    #"Filtered Type" = Table.SelectRows(dbo_Fact_Part_Transactions, each ([Type] = "C" or [Type] = "I")),
				    CutoffDate = Date.AddYears(Date.From(DateTime.LocalNow()), -7),
				    #"Filtered Date" = Table.SelectRows(#"Filtered Type", each Date.From([TransactionDate]) >= CutoffDate),
				    #"Selected Columns" = Table.SelectColumns(#"Filtered Date", {
				        "TransactionDate", "FranchiseKey", "PartNumberKey",
				        "BranchKey", "Branch", "SaleAmount", "CostAmount", "Quantity"
				    })
				in
				    #"Selected Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

