table Fact_Part_Transactions
	lineageTag: 19d9984f-93ca-43c8-948b-74d3645ccf43

	column TransactionDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 8d29db38-f289-4d7f-9beb-5941dde2be2d
		summarizeBy: none
		sourceColumn: TransactionDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FranchiseKey
		dataType: int64
		formatString: 0
		lineageTag: ee48c933-3138-4af3-853f-3ce0e9f1ac00
		summarizeBy: none
		sourceColumn: FranchiseKey

		annotation SummarizationSetBy = Automatic

	column PartNumberKey
		dataType: int64
		formatString: 0
		lineageTag: 15a01670-83b5-4a84-93bf-f721e06d8f7d
		summarizeBy: none
		sourceColumn: PartNumberKey

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: double
		lineageTag: fd0bc0d9-e418-4206-a1ee-ed2347c3a88d
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SaleAmount
		dataType: double
		lineageTag: 4f68eca5-babf-4ddb-a059-b0d8bfb86a73
		summarizeBy: sum
		sourceColumn: SaleAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CostAmount
		dataType: double
		lineageTag: 4328178f-284a-4e50-ae50-7c86b03adb11
		summarizeBy: sum
		sourceColumn: CostAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Margin
		dataType: double
		lineageTag: 8663728a-8a1f-4c4b-80b9-e6c9a33c0f1a
		summarizeBy: sum
		sourceColumn: Margin

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MarginPercent
		dataType: double
		lineageTag: c0fd2ce5-acf5-42aa-a069-f0008724d07e
		summarizeBy: sum
		sourceColumn: MarginPercent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Year
		dataType: double
		lineageTag: 72b161e1-7905-4efd-8446-afe8876f55b7
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MonthNumber
		dataType: double
		lineageTag: 00df5681-2169-4604-a965-22633ae00839
		summarizeBy: sum
		sourceColumn: MonthNumber

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Type
		dataType: string
		lineageTag: 4230beb6-7bc3-4476-940d-5084cec3291e
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column CustomerNo
		dataType: string
		lineageTag: 7d6cd61a-3deb-4f67-a7c8-263152edc4d7
		summarizeBy: none
		sourceColumn: CustomerNo

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: 62cffd60-b188-47ab-aedc-90aa4b67c573
		summarizeBy: count
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column Territory
		dataType: string
		lineageTag: 6b3bd194-0169-4fd0-8429-efecdc3a60c4
		summarizeBy: none
		sourceColumn: Territory

		annotation SummarizationSetBy = Automatic

	column PrimaryName
		dataType: string
		lineageTag: f3880d2c-0608-43cd-98d4-ef03850a8c3e
		summarizeBy: none
		sourceColumn: PrimaryName

		annotation SummarizationSetBy = Automatic

	column TransactionDescription
		dataType: string
		lineageTag: d494c267-a342-4e6c-ba68-02438ba8908d
		summarizeBy: none
		sourceColumn: TransactionDescription

		annotation SummarizationSetBy = Automatic

	column BranchKey
		dataType: int64
		formatString: 0
		lineageTag: b2feb9dc-7645-4c9d-bd42-0e5d04c4f4e0
		summarizeBy: count
		sourceColumn: BranchKey

		annotation SummarizationSetBy = Automatic

	column CustomerTradeType
		dataType: string
		lineageTag: 8ff5c950-e5a9-4379-a6d5-99aac226df0d
		summarizeBy: none
		sourceColumn: CustomerTradeType

		annotation SummarizationSetBy = Automatic

	column TransactionTradeType
		dataType: string
		lineageTag: 2dd8facd-7bf2-4e25-aa77-c96a9551eb29
		summarizeBy: none
		sourceColumn: TransactionTradeType

		annotation SummarizationSetBy = Automatic

	column SellPrice1
		dataType: double
		lineageTag: 7ab9344e-18d4-43ad-90e4-d7833b0606b7
		summarizeBy: sum
		sourceColumn: SellPrice1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ListPrice
		dataType: double
		lineageTag: dcf8737f-7b31-49a7-8b06-5cc8090187fc
		summarizeBy: sum
		sourceColumn: ListPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ListSaleVal
		dataType: double
		lineageTag: c2cf99ff-cd0b-4f85-a6ad-7887a716246d
		summarizeBy: sum
		sourceColumn: ListSaleVal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SellPrice1SaleVal
		dataType: double
		lineageTag: 29feb1a9-cb17-4f80-8de6-5d96c7c1904b
		summarizeBy: sum
		sourceColumn: SellPrice1SaleVal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '% Change'
		dataType: double
		lineageTag: cdcc9f1e-8d12-4b12-be37-8184e09f9dd0
		summarizeBy: sum
		sourceColumn: % Change

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EffectiveListSalVal
		dataType: double
		lineageTag: e6e8a574-351a-4e3d-bbab-6413b77d5dbd
		summarizeBy: sum
		sourceColumn: EffectiveListSalVal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EffectiveListMargin
		dataType: double
		lineageTag: 4c114748-406b-4ffb-abd6-7908abbbbc6f
		summarizeBy: sum
		sourceColumn: EffectiveListMargin

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EffectiveListMargin%
		dataType: double
		lineageTag: 6e9eb365-5a71-430b-944c-b08d26f0fb1b
		summarizeBy: sum
		sourceColumn: EffectiveListMargin%

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MatrixSaleGained
		dataType: double
		lineageTag: a1c0486a-6658-4000-8f26-77e0aa7ae007
		summarizeBy: sum
		sourceColumn: MatrixSaleGained

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MatrixMarginGained
		dataType: double
		lineageTag: 765284f9-81c8-4f8f-8bee-3f402ac0f99a
		summarizeBy: sum
		sourceColumn: MatrixMarginGained

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Branch
		dataType: string
		lineageTag: 6d1fc259-cb67-4697-b16a-4d3edd3cafc6
		summarizeBy: none
		sourceColumn: Branch

		annotation SummarizationSetBy = Automatic

	column IsUniqueCustomer
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8c13dcf6-6eb7-489b-b5c6-952ffc7e08ea
		summarizeBy: none
		sourceColumn: IsUniqueCustomer

		annotation SummarizationSetBy = Automatic

	column JobCode
		dataType: string
		lineageTag: 698d5470-ab64-46ff-9e98-2cd6c7d46653
		summarizeBy: none
		sourceColumn: JobCode

		annotation SummarizationSetBy = Automatic

	column JobType
		dataType: string
		lineageTag: 5e555cc0-3686-49ea-9632-effd1bb4d802
		summarizeBy: none
		sourceColumn: JobType

		annotation SummarizationSetBy = Automatic

	column UniqueCustomerType
		dataType: string
		lineageTag: 657a9863-5b9a-4f9c-a71c-0ad5c7980659
		summarizeBy: none
		sourceColumn: UniqueCustomerType

		annotation SummarizationSetBy = Automatic

	column SalesType
		dataType: string
		lineageTag: 837c4a19-94a6-466c-b915-775abd2ad69a
		summarizeBy: none
		sourceColumn: SalesType

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: 18f792aa-bb12-4b52-ba91-624b8d9614b2
		summarizeBy: sum
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column YearMonth
		dataType: int64
		formatString: 0
		lineageTag: 8e695f1b-bdfa-418f-8e5a-f5b890935a72
		summarizeBy: sum
		sourceColumn: YearMonth

		annotation SummarizationSetBy = Automatic

	column ModifiedDate
		dataType: dateTime
		formatString: General Date
		lineageTag: fcc1810a-b81b-4665-a948-092241f3681d
		summarizeBy: none
		sourceColumn: ModifiedDate

		annotation SummarizationSetBy = Automatic

	column CreationDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 23b43420-7123-450e-8f0a-13d6ea1a38f6
		summarizeBy: none
		sourceColumn: CreationDate

		annotation SummarizationSetBy = Automatic

	column TransferBranch
		dataType: string
		lineageTag: f7ffe759-a9d1-4bb0-b45e-3a0672a59c96
		summarizeBy: none
		sourceColumn: TransferBranch

		annotation SummarizationSetBy = Automatic

	column PinNo
		dataType: string
		lineageTag: 51498521-a229-4cef-8586-d8151093be37
		summarizeBy: none
		sourceColumn: PinNo

		annotation SummarizationSetBy = Automatic

	column BillToAcc
		dataType: int64
		formatString: 0
		lineageTag: c867358d-8818-4682-a81d-bda4a440829b
		summarizeBy: sum
		sourceColumn: BillToAcc

		annotation SummarizationSetBy = Automatic

	column SaleTax
		dataType: double
		lineageTag: 9816c237-50ed-4d3e-9e9d-4640c44936eb
		summarizeBy: sum
		sourceColumn: SaleTax

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SaleClass
		dataType: string
		lineageTag: 4048db0e-e14d-4f85-b8a4-c4f37443797c
		summarizeBy: none
		sourceColumn: SaleClass

		annotation SummarizationSetBy = Automatic

	column BackOrdQty
		dataType: double
		lineageTag: 7249bc88-9419-416e-a638-9d1e75867a83
		summarizeBy: sum
		sourceColumn: BackOrdQty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OriginalInvoiceNo
		dataType: string
		lineageTag: 641b4f64-839e-499f-8616-550b27fb1b49
		summarizeBy: none
		sourceColumn: OriginalInvoiceNo

		annotation SummarizationSetBy = Automatic

	column Notation
		dataType: string
		lineageTag: 9902b945-89ad-4bb5-bf97-557e1adb0753
		summarizeBy: none
		sourceColumn: Notation

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0ff4c1d5-b518-44a5-8fa6-bc4a703b9abb
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DeliveryDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: d80371d6-016f-483f-a171-ee0ad1c1d579
		summarizeBy: none
		sourceColumn: DeliveryDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column SpecialInvoiceInd
		dataType: string
		lineageTag: 742e3e37-d219-4612-b516-1ec3a7a742aa
		summarizeBy: none
		sourceColumn: SpecialInvoiceInd

		annotation SummarizationSetBy = Automatic

	column Comments
		dataType: string
		lineageTag: b8e76425-d5b5-4d47-ad55-1e1d57710716
		summarizeBy: none
		sourceColumn: Comments

		annotation SummarizationSetBy = Automatic

	column MachineId
		dataType: string
		lineageTag: d867643f-ea23-4629-820f-57c17b0a18fe
		summarizeBy: none
		sourceColumn: MachineId

		annotation SummarizationSetBy = Automatic

	column TaxCat
		dataType: string
		lineageTag: 2d771a20-c35f-4abe-a58f-810ee8c61124
		summarizeBy: none
		sourceColumn: TaxCat

		annotation SummarizationSetBy = Automatic

	column TaxedInd
		dataType: string
		lineageTag: 42474b74-4568-4abe-a157-4eed6ddc8d1e
		summarizeBy: none
		sourceColumn: TaxedInd

		annotation SummarizationSetBy = Automatic

	column ClaimedQty
		dataType: double
		lineageTag: 29d45001-c2f8-4f04-8e9c-a83cb4d2a661
		summarizeBy: sum
		sourceColumn: ClaimedQty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FileNo
		dataType: int64
		formatString: 0
		lineageTag: 8fc16bb0-409d-48ac-afa1-9ddf8a258d78
		summarizeBy: sum
		sourceColumn: FileNo

		annotation SummarizationSetBy = Automatic

	column TransId
		dataType: int64
		formatString: 0
		lineageTag: b8deda70-008c-4729-b19b-9df65621e44e
		summarizeBy: count
		sourceColumn: TransId

		annotation SummarizationSetBy = Automatic

	column Salesman
		dataType: string
		lineageTag: 42477dbf-701c-4bff-9c90-b45e293b6bb9
		summarizeBy: none
		sourceColumn: Salesman

		annotation SummarizationSetBy = Automatic

	column TaxRegion
		dataType: string
		lineageTag: 907aa918-3d8b-40af-abac-4c465beed99f
		summarizeBy: none
		sourceColumn: TaxRegion

		annotation SummarizationSetBy = Automatic

	column ImportPermitDate
		dataType: dateTime
		formatString: General Date
		lineageTag: a786f0cd-9175-4cc3-b548-eb08dce35c40
		summarizeBy: none
		sourceColumn: ImportPermitDate

		annotation SummarizationSetBy = Automatic

	column ImportPermitNo
		dataType: string
		lineageTag: 3216d7e7-07db-43ae-948b-84edaa8840ff
		summarizeBy: none
		sourceColumn: ImportPermitNo

		annotation SummarizationSetBy = Automatic

	column PortOfEntry
		dataType: string
		lineageTag: 1dfee2b4-59f6-4daf-8a15-1264e33e1786
		summarizeBy: none
		sourceColumn: PortOfEntry

		annotation SummarizationSetBy = Automatic

	column RemainingQty
		dataType: double
		lineageTag: 081c8770-26d2-4fa8-bd30-283a5eae5930
		summarizeBy: sum
		sourceColumn: RemainingQty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column InternalSalValue
		dataType: double
		lineageTag: 940c48be-b0ec-4666-8d75-097598f30406
		summarizeBy: sum
		sourceColumn: InternalSalValue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RevenueIndicator
		dataType: string
		lineageTag: bb639e95-95d5-44fb-9dd9-2a127d114f2d
		summarizeBy: none
		sourceColumn: RevenueIndicator

		annotation SummarizationSetBy = Automatic

	column StockNo
		dataType: int64
		formatString: 0
		lineageTag: 19d538ca-dbad-4325-b9b2-801fe22c7711
		summarizeBy: sum
		sourceColumn: StockNo

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: int64
		formatString: 0
		lineageTag: de1b93b9-b25c-4179-a18a-853a0c8ff57e
		summarizeBy: sum
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column OnlineOrder
		dataType: string
		lineageTag: 959ce102-d89d-4a77-a214-e0c46bf5226f
		summarizeBy: none
		sourceColumn: OnlineOrder

		annotation SummarizationSetBy = Automatic

	column PartLineStatus
		dataType: int64
		formatString: 0
		lineageTag: 788ce2af-2cbf-4088-8c4b-c70065192252
		summarizeBy: sum
		sourceColumn: PartLineStatus

		annotation SummarizationSetBy = Automatic

	column ShippingId
		dataType: int64
		formatString: 0
		lineageTag: 58986d51-56e3-49f0-bf6c-1690de3452b0
		summarizeBy: count
		sourceColumn: ShippingId

		annotation SummarizationSetBy = Automatic

	column GuidSO
		dataType: string
		lineageTag: 39eab4ab-826e-467c-a464-92afdb14d5c8
		summarizeBy: none
		sourceColumn: GuidSO

		annotation SummarizationSetBy = Automatic

	column OrderSalesman
		dataType: string
		lineageTag: 7a6f541f-938e-41f9-8d9e-6a1222de8d9d
		summarizeBy: none
		sourceColumn: OrderSalesman

		annotation SummarizationSetBy = Automatic

	column SpecialInst
		dataType: string
		lineageTag: 4527358d-26b1-4bb5-8899-8ffa648458d5
		summarizeBy: none
		sourceColumn: SpecialInst

		annotation SummarizationSetBy = Automatic

	column TransferBoInd
		dataType: string
		lineageTag: 275cec32-382a-42cb-86a9-81f2b2146c1b
		summarizeBy: none
		sourceColumn: TransferBoInd

		annotation SummarizationSetBy = Automatic

	column SoRoRef
		dataType: double
		lineageTag: 670691f5-ba6f-4f7c-850f-f17e94036600
		summarizeBy: sum
		sourceColumn: SoRoRef

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BinLocation
		dataType: string
		lineageTag: 91c7cc2c-30dd-4212-be23-b1916d7a9974
		summarizeBy: none
		sourceColumn: BinLocation

		annotation SummarizationSetBy = Automatic

	column OrderQty
		dataType: double
		lineageTag: 6f1c136e-1f32-480f-942f-8bbf2c1b03db
		summarizeBy: sum
		sourceColumn: OrderQty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ShippedQty
		dataType: double
		lineageTag: b2d26ef2-d7fa-49fd-9149-018aabb685c2
		summarizeBy: sum
		sourceColumn: ShippedQty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SubPartReceived
		dataType: string
		lineageTag: 7692d563-6ca3-4d50-bd6f-2c63d1c4817b
		summarizeBy: none
		sourceColumn: SubPartReceived

		annotation SummarizationSetBy = Automatic

	column RONumberNew
		dataType: string
		lineageTag: 20409421-c4d6-403c-ae7a-acfcd76767b3
		summarizeBy: none
		sourceColumn: RONumberNew

		annotation SummarizationSetBy = Automatic

	column WkothsubGuidSO
		dataType: string
		lineageTag: e4a47ee2-fe4d-4bf1-a397-c29f653e3e20
		summarizeBy: none
		sourceColumn: WkothsubGuidSO

		annotation SummarizationSetBy = Automatic

	column EcommOrderNo
		dataType: string
		lineageTag: 32f7c164-e56a-4d12-9f1a-2135196130b4
		summarizeBy: none
		sourceColumn: EcommOrderNo

		annotation SummarizationSetBy = Automatic

	column PartPickupFlag
		dataType: string
		lineageTag: bf0cec51-4a31-4c5c-b7f8-b8a81d2fdac6
		summarizeBy: none
		sourceColumn: PartPickupFlag

		annotation SummarizationSetBy = Automatic

	column PriceLevel
		dataType: string
		lineageTag: f02d8c51-257f-4832-a5ce-f44742b378bf
		summarizeBy: none
		sourceColumn: PriceLevel

		annotation SummarizationSetBy = Automatic

	column EpcDocId
		dataType: string
		lineageTag: f6a44a91-d7ee-4346-a083-4449e0c3a3c0
		summarizeBy: none
		sourceColumn: EpcDocId

		annotation SummarizationSetBy = Automatic

	partition Fact_Part_Transactions = m
		mode: import
		source =
				let
				    Source = Sql.Database("xcrafcusadsu3d3wi4anbgp6we-gxnyznhdptpenfw724g3o5sjzm.datawarehouse.fabric.microsoft.com", "LH_Master_Data"),
				    dbo_Fact_Part_Transactions = Source{[Schema="dbo",Item="Fact_Part_Transactions"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(dbo_Fact_Part_Transactions,{"PartNumber", "RONumber"}),
				    #"Filtered Rows" = Table.SelectRows(#"Removed Columns", each ([Type] = "C" or [Type] = "I"))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

