table 'Data Refresh'
	isHidden
	lineageTag: 16ce74a3-99ab-4318-b6eb-935c56dade83

	column CurrentDateTime
		dataType: string
		isHidden
		lineageTag: 0efcfda6-a97e-4639-8cc5-bed9bf2be73e
		summarizeBy: none
		sourceColumn: CurrentDateTime

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic
	column Date
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: c95c8056-4e6c-4f7d-81b3-094538eb0868
		summarizeBy: none
		sourceColumn: Date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic
	column Time
		dataType: dateTime
		isHidden
		formatString: Long Time
		lineageTag: d59aaca5-0d1d-4b38-a376-824a45b4f41f
		summarizeBy: none
		sourceColumn: Time

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition 'Data Refresh' = m
		mode: import
		source =
    let
        UtcNow    = DateTimeZone.UtcNow(),
        UtcDT     = DateTimeZone.RemoveZone(UtcNow),
        CurYear   = Date.Year(DateTime.Date(UtcDT)),
        Mar1      = #date(CurYear, 3, 1),
        Sun1Mar   = Date.AddDays(Mar1, Number.Mod(7 - Date.DayOfWeek(Mar1, Day.Sunday), 7)),
        DstStart  = #datetime(CurYear, 3, Date.Day(Date.AddDays(Sun1Mar, 7)), 8, 0, 0),
        Nov1      = #date(CurYear, 11, 1),
        Sun1Nov   = Date.AddDays(Nov1, Number.Mod(7 - Date.DayOfWeek(Nov1, Day.Sunday), 7)),
        DstEnd    = #datetime(CurYear, 11, Date.Day(Sun1Nov), 7, 0, 0),
        OffsetHrs = if UtcDT >= DstStart and UtcDT < DstEnd then -5 else -6,
        LocalDT   = DateTimeZone.RemoveZone(DateTimeZone.SwitchZone(UtcNow, OffsetHrs, 0)),
        Source    = #table({"CurrentDateTime"}, {{LocalDT}}),
        AddDate   = Table.DuplicateColumn(Source, "CurrentDateTime", "Date"),
        AddTime   = Table.DuplicateColumn(AddDate, "Date", "Time"),
        ChgTypes  = Table.TransformColumnTypes(AddTime, {{"Date", type date}, {"Time", type time}})
    in
        ChgTypes

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table
