table 'Inspection Goals'
	lineageTag: 1ae08b2b-585b-4e6b-b27b-168a66b26d9a

	column LOCATION
		dataType: string
		lineageTag: a30125b9-0723-4055-a2c2-bee095f2a3eb
		summarizeBy: none
		sourceColumn: LOCATION

		annotation SummarizationSetBy = Automatic

	column 'Inspections Goal'
		dataType: int64
		formatString: 0
		lineageTag: 09c7f056-cc30-482d-9bf6-19b679d3f65c
		summarizeBy: sum
		sourceColumn: Inspections Goal

		annotation SummarizationSetBy = Automatic

	column 'Labor $$ w/ Inspection Goal'
		dataType: double
		lineageTag: 9eb6fafb-823a-45a4-99f1-8044203298b3
		summarizeBy: sum
		sourceColumn: Labor $$ w/ Inspection Goal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Parts $$ Goal'
		dataType: double
		lineageTag: ebe6a1b5-d88e-4189-995f-35ebc0ab633a
		summarizeBy: sum
		sourceColumn: Total Parts $$ Goal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'CS690/770 Inspections Goal'
		dataType: double
		formatString: 0
		lineageTag: d3381aac-7ef3-483f-8348-fe2e618e7436
		summarizeBy: sum
		sourceColumn: CS690/770 Inspections Goal

		annotation SummarizationSetBy = Automatic

	column 'CS690/770 Labor $$ w/ Inspection Goal'
		dataType: double
		lineageTag: 89a74126-2f70-4d62-b535-cecec06d0a4d
		summarizeBy: sum
		sourceColumn: CS690/770 Labor $$ w/ Inspection Goal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'CS690/770 Total Parts $$ Goal'
		dataType: double
		lineageTag: 2a7f33d8-5d5b-4286-a4ee-e1e8413898ba
		summarizeBy: sum
		sourceColumn: CS690/770 Total Parts $$ Goal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Inspection Goals' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://spitractor-my.sharepoint.com/personal/bfox_spitractor_com/Documents/Power%20BI%20-%20Vis/Data/Inspection%20Goals.xlsx"), null, true),
				    Table3_Table = Source{[Item="Table3",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Table3_Table,{{"LOCATION", type text}, {"Inspections Goal", Int64.Type}, {"Labor $$ w/ Inspection Goal", type number}, {"Total Parts $$ Goal", type number}, {"CS690/770 Inspections Goal", Int64.Type}, {"CS690/770 Labor $$ w/ Inspection Goal", type number}, {"CS690/770 Total Parts $$ Goal", type number}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type",10,11,Replacer.ReplaceValue,{"CS690/770 Inspections Goal"})
				in
				    #"Replaced Value"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

