table Fact_Inventory
	lineageTag: c6fb66fb-793c-4217-b378-d7ac44b3bc11

	column BranchKey
		dataType: int64
		formatString: 0
		lineageTag: e896927e-7daf-49c0-bb57-c2c8401fa644
		summarizeBy: none
		sourceColumn: BranchKey

		annotation SummarizationSetBy = Automatic

	column PartNumber
		dataType: string
		lineageTag: a12abc78-f882-4687-beeb-e2a9478e9878
		summarizeBy: none
		sourceColumn: PartNumber

		annotation SummarizationSetBy = Automatic

	column PartNumberKey
		dataType: int64
		formatString: 0
		lineageTag: f9facfc1-e86d-45df-8a62-81d0e31d78fa
		summarizeBy: none
		sourceColumn: PartNumberKey

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 56082443-5931-4a56-a728-18c7c2512635
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column FranchiseKey
		dataType: int64
		formatString: 0
		lineageTag: 7af0926c-5e8a-4ae7-b88f-55346988dcaf
		summarizeBy: none
		sourceColumn: FranchiseKey

		annotation SummarizationSetBy = Automatic

	column VendorCodeKey
		dataType: int64
		formatString: 0
		lineageTag: c4416796-a4c9-4978-a16e-8414dc60d756
		summarizeBy: none
		sourceColumn: VendorCodeKey

		annotation SummarizationSetBy = Automatic

	column SourceKey
		dataType: int64
		formatString: 0
		lineageTag: 691ff51e-575d-44dc-85c8-0df7321bb150
		summarizeBy: none
		sourceColumn: SourceKey

		annotation SummarizationSetBy = Automatic

	column SLCKey
		dataType: int64
		formatString: 0
		lineageTag: faba04f2-7bc9-4868-af62-0ca21c6225f5
		summarizeBy: none
		sourceColumn: SLCKey

		annotation SummarizationSetBy = Automatic

	column DealerGroupKey
		dataType: int64
		formatString: 0
		lineageTag: e2d1bb6d-cac8-45f4-9a14-7ceadc2520db
		summarizeBy: none
		sourceColumn: DealerGroupKey

		annotation SummarizationSetBy = Automatic

	column CommodityCodeKey
		dataType: int64
		formatString: 0
		lineageTag: 17ade9f6-cb18-46f5-857b-f7b90cd9e848
		summarizeBy: count
		sourceColumn: CommodityCodeKey

		annotation SummarizationSetBy = Automatic

	column InventoryCost
		dataType: double
		lineageTag: 19a7725e-b6c1-44bb-b6e1-9ce4907f53bf
		summarizeBy: sum
		sourceColumn: InventoryCost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BinQty
		dataType: double
		lineageTag: 7e858a9c-16e7-4a5e-95e1-1cb781f1394d
		summarizeBy: sum
		sourceColumn: BinQty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QuantityOnHand
		dataType: double
		lineageTag: c84dece1-228f-47fb-9618-b88f27106a84
		summarizeBy: sum
		sourceColumn: QuantityOnHand

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BackOrderQty
		dataType: double
		lineageTag: 0044902c-8746-486d-9123-1a751eae5b00
		summarizeBy: sum
		sourceColumn: BackOrderQty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SellPrice1
		dataType: double
		lineageTag: 0245b11a-f241-48ba-a718-b123cfb9f780
		summarizeBy: sum
		sourceColumn: SellPrice1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Cost
		dataType: double
		lineageTag: 3f00b370-28da-47af-8b49-6b1f0e5af4b4
		summarizeBy: sum
		sourceColumn: Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Current12MoSales
		dataType: double
		lineageTag: 17ec3ad3-867d-4c70-85e2-196181138ee6
		summarizeBy: sum
		sourceColumn: Current12MoSales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Current12MoDollars
		dataType: double
		lineageTag: 722c2385-f85f-4321-80e9-5a95f592724b
		summarizeBy: sum
		sourceColumn: Current12MoDollars

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DateCreated
		dataType: dateTime
		formatString: General Date
		lineageTag: 87e73c96-78d9-40de-b012-2edf6e9edd3b
		summarizeBy: none
		sourceColumn: DateCreated

		annotation SummarizationSetBy = Automatic

	column DateLastRequested
		dataType: dateTime
		formatString: General Date
		lineageTag: e0e62776-d229-423c-af80-e4749deefba2
		summarizeBy: none
		sourceColumn: DateLastRequested

		annotation SummarizationSetBy = Automatic

	column ListPrice
		dataType: double
		lineageTag: ccb26b45-bd08-4136-bed5-716603e5ea47
		summarizeBy: sum
		sourceColumn: ListPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Returnable
		dataType: string
		lineageTag: 15679158-0172-49d5-b85b-e968a1726e55
		summarizeBy: none
		sourceColumn: Returnable

		annotation SummarizationSetBy = Automatic

	column Previous12MoSales
		dataType: double
		lineageTag: 04e16f1f-0ef1-449e-a055-f8e92424ea36
		summarizeBy: sum
		sourceColumn: Previous12MoSales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Previous12MoDollars
		dataType: double
		lineageTag: 8d700135-ef16-4b3a-bc1b-98d62845d638
		summarizeBy: sum
		sourceColumn: Previous12MoDollars

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PackageQty
		dataType: int64
		formatString: 0
		lineageTag: 0f962f5a-ac1f-4343-83a3-4ab9663a8b79
		summarizeBy: sum
		sourceColumn: PackageQty

		annotation SummarizationSetBy = Automatic

	partition Fact_Inventory = m
		mode: import
		source =
				let
				    Source = Sql.Database("xcrafcusadsu3d3wi4anbgp6we-gxnyznhdptpenfw724g3o5sjzm.datawarehouse.fabric.microsoft.com", "LH_Master_Data"),
				    dbo_Fact_Inventory = Source{[Schema="dbo",Item="Fact_Inventory"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(dbo_Fact_Inventory, each ([FranchiseKey] = 7))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

