table Fact_Part_Transactions
	lineageTag: 7c56d07c-e483-4676-a4dd-a647632d5b06

	column TransactionDate
		dataType: dateTime
		formatString: Short Date
		lineageTag: 5b57c14e-7033-4a42-9503-c932ebf365b8
		summarizeBy: none
		sourceColumn: TransactionDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CustomerNo
		dataType: string
		lineageTag: 0fb37206-31cf-4f2c-a01d-eb337d9401e5
		summarizeBy: none
		sourceColumn: CustomerNo

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: 63f8af4c-9567-468e-8f30-043e320d9c41
		summarizeBy: count
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column Territory
		dataType: string
		lineageTag: e729d3bb-6699-4848-b4e1-9ed2d23c6502
		summarizeBy: none
		sourceColumn: Territory

		annotation SummarizationSetBy = Automatic

	column PrimaryName
		dataType: string
		lineageTag: 45f2d897-627e-44ff-bb1e-e3e25c8dd63e
		summarizeBy: none
		sourceColumn: PrimaryName

		annotation SummarizationSetBy = Automatic

	column FranchiseKey
		dataType: int64
		formatString: 0
		lineageTag: c8919e5f-8f11-46f9-9ca8-af8c03c61fef
		summarizeBy: none
		sourceColumn: FranchiseKey

		annotation SummarizationSetBy = Automatic

	column PartNumber
		dataType: string
		lineageTag: f72b769f-8dad-4696-a5ff-7edaea098569
		summarizeBy: none
		sourceColumn: PartNumber

		annotation SummarizationSetBy = Automatic

	column PartNumberKey
		dataType: int64
		formatString: 0
		lineageTag: 63505e45-e8ce-4d23-8a60-174636548189
		summarizeBy: none
		sourceColumn: PartNumberKey

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: double
		lineageTag: eb5dde30-0c97-4519-bd88-19c007dae177
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Type
		dataType: string
		lineageTag: 93583599-251c-4fe5-b8b4-e1c05a107729
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column RONumber
		dataType: string
		lineageTag: 4aa787ec-cce7-4a52-9225-447ef5f134e3
		summarizeBy: none
		sourceColumn: RONumber

		annotation SummarizationSetBy = Automatic

	column TransactionDescription
		dataType: string
		lineageTag: 4ba7db2b-bfb0-4e9c-a1de-89c582758582
		summarizeBy: none
		sourceColumn: TransactionDescription

		annotation SummarizationSetBy = Automatic

	column SaleAmount
		dataType: double
		lineageTag: 0ab5f072-bbfd-4321-ba9e-8dce224ebf5e
		summarizeBy: sum
		sourceColumn: SaleAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CostAmount
		dataType: double
		lineageTag: 9ce346cc-eae2-4d52-af33-59244f36cbc4
		summarizeBy: sum
		sourceColumn: CostAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Margin
		dataType: double
		lineageTag: ecd15928-9c39-4240-a9a5-3cd0d7c85640
		summarizeBy: sum
		sourceColumn: Margin

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MarginPercent
		dataType: double
		lineageTag: 705f9a30-6737-4abc-bbd0-78b1216968cf
		summarizeBy: sum
		sourceColumn: MarginPercent

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Year
		dataType: double
		lineageTag: ba66ef0e-0e28-4b5b-9a71-9bbcb06f6462
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MonthNumber
		dataType: double
		lineageTag: 6c7a762f-e61d-4fd8-bd20-b03b4aebf153
		summarizeBy: sum
		sourceColumn: MonthNumber

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BranchKey
		dataType: int64
		formatString: 0
		lineageTag: 4e94c6b2-a424-433b-8e0a-fe1d3f49c352
		summarizeBy: none
		sourceColumn: BranchKey

		annotation SummarizationSetBy = Automatic

	column CustomerTradeType
		dataType: string
		lineageTag: 44e08842-3ce1-492c-a5c1-c650b88f6a19
		summarizeBy: none
		sourceColumn: CustomerTradeType

		annotation SummarizationSetBy = Automatic

	column TransactionTradeType
		dataType: string
		lineageTag: 1a467ed2-92af-43fe-b73b-e5261807d7f9
		summarizeBy: none
		sourceColumn: TransactionTradeType

		annotation SummarizationSetBy = Automatic

	column SellPrice1
		dataType: double
		lineageTag: 904be9f1-cd97-4098-ae9a-1c2b66594481
		summarizeBy: sum
		sourceColumn: SellPrice1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ListPrice
		dataType: double
		lineageTag: a606b372-86ed-4e36-bd65-4241b78fe54c
		summarizeBy: sum
		sourceColumn: ListPrice

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ListSaleVal
		dataType: double
		lineageTag: 565c1da4-3dc3-40e1-abea-39778591fc14
		summarizeBy: sum
		sourceColumn: ListSaleVal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SellPrice1SaleVal
		dataType: double
		lineageTag: 2c430c3a-192c-4876-b8bc-8b8518d74000
		summarizeBy: sum
		sourceColumn: SellPrice1SaleVal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column '% Change'
		dataType: double
		lineageTag: e67be00b-a0db-4a8f-9fa2-54c623b7886d
		summarizeBy: sum
		sourceColumn: % Change

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EffectiveListSalVal
		dataType: double
		lineageTag: 623144a1-c4c5-4ac1-9c8f-012238621aef
		summarizeBy: sum
		sourceColumn: EffectiveListSalVal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EffectiveListMargin
		dataType: double
		lineageTag: a216f548-d070-4e41-8f9e-2978b299a912
		summarizeBy: sum
		sourceColumn: EffectiveListMargin

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EffectiveListMargin%
		dataType: double
		lineageTag: 14f21cc0-a782-4855-993b-1cb2fb759cc5
		summarizeBy: sum
		sourceColumn: EffectiveListMargin%

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MatrixSaleGained
		dataType: double
		lineageTag: 0deeca01-5055-4223-a2a5-89e425b2b179
		summarizeBy: sum
		sourceColumn: MatrixSaleGained

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MatrixMarginGained
		dataType: double
		lineageTag: 24f1cfec-17bb-47fd-a4a4-827cfa1d0dfb
		summarizeBy: sum
		sourceColumn: MatrixMarginGained

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Branch
		dataType: string
		lineageTag: b57f1eda-14b7-4e6a-ba0c-ae669285f58e
		summarizeBy: none
		sourceColumn: Branch

		annotation SummarizationSetBy = Automatic

	column IsUniqueCustomer
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 688f0b1c-33de-4723-8cc5-38387cd10a72
		summarizeBy: none
		sourceColumn: IsUniqueCustomer

		annotation SummarizationSetBy = Automatic

	column JobCode
		dataType: string
		lineageTag: 19033205-e73e-482b-97dd-0e72c8d9f61a
		summarizeBy: none
		sourceColumn: JobCode

		annotation SummarizationSetBy = Automatic

	column JobType
		dataType: string
		lineageTag: 086e9199-9665-44d1-b5f3-9577934e7019
		summarizeBy: none
		sourceColumn: JobType

		annotation SummarizationSetBy = Automatic

	column UniqueCustomerType
		dataType: string
		lineageTag: f11a2b79-b5e5-49a8-8368-f5f7f824103f
		summarizeBy: none
		sourceColumn: UniqueCustomerType

		annotation SummarizationSetBy = Automatic

	column SalesType
		dataType: string
		lineageTag: 5f14e698-46f3-4b30-8da7-610a0ca9b6e9
		summarizeBy: none
		sourceColumn: SalesType

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: int64
		formatString: 0
		lineageTag: 910e068e-ed5f-4cc0-94e0-f99f57459176
		summarizeBy: sum
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column YearMonth
		dataType: int64
		formatString: 0
		lineageTag: df93f0b4-16c7-4fda-bbfb-3b003cdefafc
		summarizeBy: sum
		sourceColumn: YearMonth

		annotation SummarizationSetBy = Automatic

	column ModifiedDate
		dataType: dateTime
		formatString: General Date
		lineageTag: fc5c5b26-57e7-4eea-a590-800820bce3ff
		summarizeBy: none
		sourceColumn: ModifiedDate

		annotation SummarizationSetBy = Automatic

	column CreationDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 88567202-3e9d-44fe-bb4e-a811f8a06d1d
		summarizeBy: none
		sourceColumn: CreationDate

		annotation SummarizationSetBy = Automatic

	column TransferBranch
		dataType: string
		lineageTag: 5ac06534-7a50-4c04-b1fa-105295ecd6b7
		summarizeBy: none
		sourceColumn: TransferBranch

		annotation SummarizationSetBy = Automatic

	column PinNo
		dataType: string
		lineageTag: c46f5177-8d43-47bf-928b-b8027dd16981
		summarizeBy: none
		sourceColumn: PinNo

		annotation SummarizationSetBy = Automatic

	column BillToAcc
		dataType: int64
		formatString: 0
		lineageTag: 7db6a378-5cc1-42e2-9d69-44ab78abe381
		summarizeBy: sum
		sourceColumn: BillToAcc

		annotation SummarizationSetBy = Automatic

	column SaleTax
		dataType: double
		lineageTag: 294ee4d4-2eb1-4dd7-845f-76f659a9397f
		summarizeBy: sum
		sourceColumn: SaleTax

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SaleClass
		dataType: string
		lineageTag: c7e7badd-37d8-45e3-935e-8e217b5fd376
		summarizeBy: none
		sourceColumn: SaleClass

		annotation SummarizationSetBy = Automatic

	column BackOrdQty
		dataType: double
		lineageTag: 564ece09-96b0-4758-abdc-e1f4f85468c9
		summarizeBy: sum
		sourceColumn: BackOrdQty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OriginalInvoiceNo
		dataType: string
		lineageTag: 1a55c743-2072-4da8-95a1-799b69db73b3
		summarizeBy: none
		sourceColumn: OriginalInvoiceNo

		annotation SummarizationSetBy = Automatic

	column Notation
		dataType: string
		lineageTag: 41bf01fc-52cd-4c6b-b8ab-f92d3375ee38
		summarizeBy: none
		sourceColumn: Notation

		annotation SummarizationSetBy = Automatic

	column OrderDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: c04f1bab-869c-44d8-9687-1dddf4c52479
		summarizeBy: none
		sourceColumn: OrderDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column DeliveryDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 34f94ce5-71e8-4f9c-9cef-7b5a4ef1408f
		summarizeBy: none
		sourceColumn: DeliveryDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column SpecialInvoiceInd
		dataType: string
		lineageTag: 56f9632a-c21c-4662-8a53-c736b39723dc
		summarizeBy: none
		sourceColumn: SpecialInvoiceInd

		annotation SummarizationSetBy = Automatic

	column Comments
		dataType: string
		lineageTag: 9add8f3d-4397-4530-adfc-b1b1230d98c4
		summarizeBy: none
		sourceColumn: Comments

		annotation SummarizationSetBy = Automatic

	column MachineId
		dataType: string
		lineageTag: 798db410-6bbb-42d9-881a-15e39922fb25
		summarizeBy: none
		sourceColumn: MachineId

		annotation SummarizationSetBy = Automatic

	column TaxCat
		dataType: string
		lineageTag: f5607d99-a363-4868-a744-b9da4d3e28fc
		summarizeBy: none
		sourceColumn: TaxCat

		annotation SummarizationSetBy = Automatic

	column TaxedInd
		dataType: string
		lineageTag: ee6ca832-4355-4875-af8b-2a3e75239bbe
		summarizeBy: none
		sourceColumn: TaxedInd

		annotation SummarizationSetBy = Automatic

	column ClaimedQty
		dataType: double
		lineageTag: 24a389a7-24a6-4757-b122-61aeb7c92481
		summarizeBy: sum
		sourceColumn: ClaimedQty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FileNo
		dataType: int64
		formatString: 0
		lineageTag: 82c4cea1-0bd1-4a98-91e5-a940e8a58d52
		summarizeBy: sum
		sourceColumn: FileNo

		annotation SummarizationSetBy = Automatic

	column TransId
		dataType: int64
		formatString: 0
		lineageTag: 9d4ad90b-7a49-4ab2-8e43-1986591d60a9
		summarizeBy: count
		sourceColumn: TransId

		annotation SummarizationSetBy = Automatic

	column Salesman
		dataType: string
		lineageTag: 82716e3b-675b-4d19-9ee5-5c6cb42df219
		summarizeBy: none
		sourceColumn: Salesman

		annotation SummarizationSetBy = Automatic

	column TaxRegion
		dataType: string
		lineageTag: 4f4bb3f1-1599-4f71-88ba-ae224c122ff1
		summarizeBy: none
		sourceColumn: TaxRegion

		annotation SummarizationSetBy = Automatic

	column ImportPermitDate
		dataType: dateTime
		formatString: General Date
		lineageTag: 2434171c-748a-440c-b336-f662a6025082
		summarizeBy: none
		sourceColumn: ImportPermitDate

		annotation SummarizationSetBy = Automatic

	column ImportPermitNo
		dataType: string
		lineageTag: 7da67dfb-4163-45c7-be8c-bd883d07f002
		summarizeBy: none
		sourceColumn: ImportPermitNo

		annotation SummarizationSetBy = Automatic

	column PortOfEntry
		dataType: string
		lineageTag: 1bfe9a8f-43eb-46c2-8b9c-30ffed06c24a
		summarizeBy: none
		sourceColumn: PortOfEntry

		annotation SummarizationSetBy = Automatic

	column RemainingQty
		dataType: double
		lineageTag: 868c4ae3-8744-4a12-b3c6-7f9f97312f47
		summarizeBy: sum
		sourceColumn: RemainingQty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column InternalSalValue
		dataType: double
		lineageTag: c9001abd-11d2-4c72-be45-9d3711224407
		summarizeBy: sum
		sourceColumn: InternalSalValue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RevenueIndicator
		dataType: string
		lineageTag: 92a6e73c-7dc1-4af0-b4ed-fb51e5d28cd1
		summarizeBy: none
		sourceColumn: RevenueIndicator

		annotation SummarizationSetBy = Automatic

	column StockNo
		dataType: int64
		formatString: 0
		lineageTag: e10558f7-e894-4920-9dad-85ffb381f59b
		summarizeBy: sum
		sourceColumn: StockNo

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: int64
		formatString: 0
		lineageTag: e8f55697-cdf7-4f6a-b0c7-cff65bbb2368
		summarizeBy: sum
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column OnlineOrder
		dataType: string
		lineageTag: 598fd599-f097-497f-a052-71d1dbb68517
		summarizeBy: none
		sourceColumn: OnlineOrder

		annotation SummarizationSetBy = Automatic

	column PartLineStatus
		dataType: int64
		formatString: 0
		lineageTag: 54cb907a-60b9-4dd4-a45e-2abd36e4066b
		summarizeBy: sum
		sourceColumn: PartLineStatus

		annotation SummarizationSetBy = Automatic

	column ShippingId
		dataType: int64
		formatString: 0
		lineageTag: 72ead53a-a35a-4e12-aca5-4317f6a61a1e
		summarizeBy: count
		sourceColumn: ShippingId

		annotation SummarizationSetBy = Automatic

	column GuidSO
		dataType: string
		lineageTag: debb85d9-7c6a-408e-a2e5-b55fd0b16d26
		summarizeBy: none
		sourceColumn: GuidSO

		annotation SummarizationSetBy = Automatic

	column OrderSalesman
		dataType: string
		lineageTag: 8d4515de-8038-4495-a261-a42456981cf0
		summarizeBy: none
		sourceColumn: OrderSalesman

		annotation SummarizationSetBy = Automatic

	column SpecialInst
		dataType: string
		lineageTag: ff373932-6b84-47ac-a453-6251fba747b7
		summarizeBy: none
		sourceColumn: SpecialInst

		annotation SummarizationSetBy = Automatic

	column TransferBoInd
		dataType: string
		lineageTag: 4c8dbc67-ce20-4dc1-847d-fa73f2ff2b4b
		summarizeBy: none
		sourceColumn: TransferBoInd

		annotation SummarizationSetBy = Automatic

	column SoRoRef
		dataType: double
		lineageTag: 6bd6f9a8-95f4-4fc3-bba7-3702f2ecfe97
		summarizeBy: sum
		sourceColumn: SoRoRef

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BinLocation
		dataType: string
		lineageTag: 8ca69ded-55f9-4214-b948-39c66e56e45b
		summarizeBy: none
		sourceColumn: BinLocation

		annotation SummarizationSetBy = Automatic

	column OrderQty
		dataType: double
		lineageTag: 6494b16d-f6c4-4d73-9dbe-4044951a61c9
		summarizeBy: sum
		sourceColumn: OrderQty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ShippedQty
		dataType: double
		lineageTag: 0cfcb1e7-e41f-4d50-91f2-b1789a7510ce
		summarizeBy: sum
		sourceColumn: ShippedQty

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SubPartReceived
		dataType: string
		lineageTag: b701873d-ac46-4e92-9130-c8fa379e9dd8
		summarizeBy: none
		sourceColumn: SubPartReceived

		annotation SummarizationSetBy = Automatic

	column RONumberNew
		dataType: string
		lineageTag: 1dac1eb5-551f-408b-9233-69c7b3cfce19
		summarizeBy: none
		sourceColumn: RONumberNew

		annotation SummarizationSetBy = Automatic

	column WkothsubGuidSO
		dataType: string
		lineageTag: 2bc7fa95-507f-40e7-9422-35daec0bdcdb
		summarizeBy: none
		sourceColumn: WkothsubGuidSO

		annotation SummarizationSetBy = Automatic

	column EcommOrderNo
		dataType: string
		lineageTag: a1271561-3fef-4157-9ef5-c5001d621148
		summarizeBy: none
		sourceColumn: EcommOrderNo

		annotation SummarizationSetBy = Automatic

	column PartPickupFlag
		dataType: string
		lineageTag: 42b3b6b4-3861-4953-86e3-58c409e35063
		summarizeBy: none
		sourceColumn: PartPickupFlag

		annotation SummarizationSetBy = Automatic

	column PriceLevel
		dataType: string
		lineageTag: 7fa4961f-7a79-41ec-8f32-4a3a593fe893
		summarizeBy: none
		sourceColumn: PriceLevel

		annotation SummarizationSetBy = Automatic

	column EpcDocId
		dataType: string
		lineageTag: 478cdfd3-3db2-4f8e-8819-7d65f6097658
		summarizeBy: none
		sourceColumn: EpcDocId

		annotation SummarizationSetBy = Automatic

	partition Fact_Part_Transactions = m
		mode: import
		source =
				let
				    Source = Sql.Database("xcrafcusadsu3d3wi4anbgp6we-gxnyznhdptpenfw724g3o5sjzm.datawarehouse.fabric.microsoft.com", "LH_Master_Data"),
				    dbo_Fact_Part_Transactions = Source{[Schema="dbo",Item="Fact_Part_Transactions"]}[Data],
				    FilteredRows = Table.SelectRows(dbo_Fact_Part_Transactions, each [TransactionDate] >= Date.AddMonths(Date.From(DateTime.LocalNow()), -13)),
				    #"Filtered Rows" = Table.SelectRows(FilteredRows, each ([FranchiseKey] = 7) and ([Type] = "C" or [Type] = "I"))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

