table Price_Matrix
	lineageTag: 6f8ab1cc-e912-4730-af06-d2043c455521

	column price_admin_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 507fa532-93f8-497e-92da-f40777034954
		summarizeBy: sum
		sourceColumn: price_admin_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column branch
		dataType: string
		isHidden
		lineageTag: 42761006-a55b-49d2-9683-88db8e69033f
		summarizeBy: none
		sourceColumn: branch

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column franchise
		dataType: string
		isHidden
		lineageTag: d9d824f7-eef6-4de5-aa7e-34fa0211520a
		summarizeBy: none
		sourceColumn: franchise

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column vendor_code
		dataType: string
		isHidden
		lineageTag: 6cdd4049-e0c4-40ce-97fc-451617dee70d
		summarizeBy: none
		sourceColumn: vendor_code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column vendor_name
		dataType: string
		isHidden
		lineageTag: 21fdb6e8-1f89-43ba-a61c-5ea60e0aca9d
		summarizeBy: none
		sourceColumn: vendor_name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column price_admin_code_type
		dataType: string
		isHidden
		lineageTag: 5f007600-2cb4-47bd-9903-d5ad17f3dc18
		summarizeBy: none
		sourceColumn: price_admin_code_type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column price_admin_code
		dataType: string
		isHidden
		lineageTag: 03514513-c666-4903-9441-5d0d6d31921e
		summarizeBy: none
		sourceColumn: price_admin_code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column price_type
		dataType: string
		isHidden
		lineageTag: 20ba6a2d-2546-4aaf-ae44-3da4d918e33c
		summarizeBy: none
		sourceColumn: price_type

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column value_from
		dataType: double
		lineageTag: 7b80a704-13bb-4969-ab87-e4c6300a1fbc
		summarizeBy: sum
		sourceColumn: value_from

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column value_to
		dataType: double
		lineageTag: a39d3010-fe39-4c9f-a50e-ba91cc5812d9
		summarizeBy: sum
		sourceColumn: value_to

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column include_exchange_part
		dataType: string
		isHidden
		lineageTag: b95599bc-2943-4a13-9366-63b0b1cd860e
		summarizeBy: none
		sourceColumn: include_exchange_part

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column price_based_on
		dataType: string
		isHidden
		lineageTag: db0f92b9-8550-4fac-bb51-2d406d687615
		summarizeBy: none
		sourceColumn: price_based_on

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column price_percent
		dataType: double
		formatString: 0.00
		lineageTag: 65776c7e-05ea-4015-9de4-ec71e0a9fce8
		summarizeBy: sum
		sourceColumn: price_percent

		annotation SummarizationSetBy = Automatic

	column exchange_part_price_percent
		dataType: string
		isHidden
		lineageTag: 5ad67003-517b-4e09-8038-715761cd7c7a
		summarizeBy: none
		sourceColumn: exchange_part_price_percent

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column created_by
		dataType: string
		isHidden
		lineageTag: 914e5b54-3437-4112-a622-ae53702eb6a8
		summarizeBy: none
		sourceColumn: created_by

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column created_date
		dataType: string
		isHidden
		lineageTag: e534f4c2-e00b-4fda-a3ae-5cc75e1d49bd
		summarizeBy: none
		sourceColumn: created_date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column modified_by
		dataType: string
		isHidden
		lineageTag: ae69544d-24f0-4252-9089-9ea9843dea79
		summarizeBy: none
		sourceColumn: modified_by

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column modified_date
		dataType: string
		isHidden
		lineageTag: 6ff4c7a5-0d21-4c0f-a773-3755b853513c
		summarizeBy: none
		sourceColumn: modified_date

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column select_all
		dataType: string
		isHidden
		lineageTag: 3ef14140-dac1-4775-bd1c-c3d6c6978d7e
		summarizeBy: none
		sourceColumn: select_all

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column dup
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c28bc14b-eef3-4d2b-b9b7-42f6f46d806a
		summarizeBy: sum
		sourceColumn: dup

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Range = "$" & FORMAT([value_from], "#,##0.00") & " - $" & FORMAT([value_to], "#,##0.00")
		lineageTag: 00fc745e-da87-4394-9d8f-0dad1dbdd904
		summarizeBy: none
		sortByColumn: 'Range Sort'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Range Sort' = [value_from]
		lineageTag: 7b5e0480-6e01-48f5-8ac6-d8c3643b9aca
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Markup = [price_percent] / 100
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: aedbacaf-40d2-4af8-b8dc-37a0b87490de
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition Price_Matrix = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://spitractor-my.sharepoint.com/personal/bfox_spitractor_com/Documents/Power%20BI%20-%20Vis/Data/PRICE%20MATRIX%207-9-25.csv"),[Delimiter=",", Columns=20, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"price_admin_id", Int64.Type}, {"branch", type text}, {"franchise", type text}, {"vendor_code", type text}, {"vendor_name", type text}, {"price_admin_code_type", type text}, {"price_admin_code", type text}, {"price_type", type text}, {"value_from", type number}, {"value_to", type number}, {"include_exchange_part", type text}, {"price_based_on", type text}, {"price_percent", type number}, {"exchange_part_price_percent", type text}, {"created_by", type text}, {"created_date", type text}, {"modified_by", type text}, {"modified_date", type text}, {"select_all", type text}, {"dup", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

