table Inv_Snapshot
	lineageTag: d1e2f3a4-0001-4000-8000-000000000001

	column Branch
		dataType: string
		lineageTag: d1e2f3a4-0002-4000-8000-000000000002
		summarizeBy: none
		sourceColumn: Branch

		annotation SummarizationSetBy = Automatic

	column PartNumber
		dataType: string
		lineageTag: d1e2f3a4-0003-4000-8000-000000000003
		summarizeBy: none
		sourceColumn: PartNumber

		annotation SummarizationSetBy = Automatic

	column QuantityOnHand
		dataType: double
		formatString: #,0
		lineageTag: d1e2f3a4-0004-4000-8000-000000000004
		summarizeBy: sum
		sourceColumn: QuantityOnHand

		annotation SummarizationSetBy = Automatic

	column InventoryCost
		dataType: double
		formatString: $#,##0.00
		lineageTag: d1e2f3a4-0005-4000-8000-000000000005
		summarizeBy: sum
		sourceColumn: InventoryCost

		annotation SummarizationSetBy = Automatic

	partition Inv_Snapshot = m
		mode: import
		source =
				let
				    Source = Sql.Database("xcrafcusadsu3d3wi4anbgp6we-gxnyznhdptpenfw724g3o5sjzm.datawarehouse.fabric.microsoft.com", "LH_Master_Data"),
				    jdis_Part_Information = Source{[Schema="dbo",Item="jdis_Part_Information"]}[Data],
				    SelectColumns = Table.SelectColumns(jdis_Part_Information, {"Branch", "PartNumber", "QuantityOnHand", "InventoryCost"}),
				    FilterZero = Table.SelectRows(SelectColumns, each [InventoryCost] <> 0)
				in
				    FilterZero

	annotation PBI_Id = Inv_Snapshot

