table Fact_InTrans
	lineageTag: a2af5df5-4297-4fe4-a962-da78e1a74528

	column TransId
		dataType: int64
		formatString: 0
		lineageTag: 8b09ab1b-03ae-4ed9-ac5d-455072b1ea5c
		summarizeBy: count
		sourceColumn: TransId

		annotation SummarizationSetBy = Automatic

	column RONumber
		dataType: string
		lineageTag: 1a107ec4-8f4b-4198-bd1f-17c44dfbc7bd
		summarizeBy: none
		sourceColumn: RONumber

		annotation SummarizationSetBy = Automatic

	column TransDatetime
		dataType: dateTime
		formatString: Short Date
		lineageTag: 2cfa55e4-ba9c-443c-85df-39c3c2d48359
		summarizeBy: none
		sourceColumn: TransDatetime

		annotation SummarizationSetBy = Automatic

	column Branch
		dataType: string
		lineageTag: 91aaf8ab-d135-4b6a-9698-6d2bfcb6dc0b
		summarizeBy: none
		sourceColumn: Branch

		annotation SummarizationSetBy = Automatic

	column PartNumber
		dataType: string
		lineageTag: 58b2a8f5-46d2-4506-bfab-d8f3c94b67ad
		summarizeBy: none
		sourceColumn: PartNumber

		annotation SummarizationSetBy = Automatic

	column Franchise
		dataType: string
		lineageTag: 32802e39-2b91-4ba5-b724-231731e21b1c
		summarizeBy: none
		sourceColumn: Franchise

		annotation SummarizationSetBy = Automatic

	column CustomerNo
		dataType: string
		lineageTag: 5f176929-2640-49d4-9c67-6051ecb712d3
		summarizeBy: none
		sourceColumn: CustomerNo

		annotation SummarizationSetBy = Automatic

	column Salesman
		dataType: string
		lineageTag: 9ebf7e53-3c63-4bae-9a8c-191dd4ca80a8
		summarizeBy: none
		sourceColumn: Salesman

		annotation SummarizationSetBy = Automatic

	column Type
		dataType: string
		lineageTag: 5f7052a4-5c97-4cb8-a479-747a45f11a46
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column Qty
		dataType: double
		formatString: 0
		lineageTag: 9cbd1572-c8ff-4c5a-bf01-108738961c6f
		summarizeBy: sum
		sourceColumn: Qty

		annotation SummarizationSetBy = Automatic

	column SaleValue
		dataType: double
		lineageTag: fd09df1e-7c0a-48a0-ba10-ba4a081cc2be
		summarizeBy: sum
		sourceColumn: SaleValue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CostValue
		dataType: double
		lineageTag: fca494e0-497a-48e6-b813-150ab4241ba7
		summarizeBy: sum
		sourceColumn: CostValue

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Description
		dataType: string
		lineageTag: 8691a025-ec26-47ac-a54b-fab0d2aec5ee
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column TradeType
		dataType: string
		lineageTag: 507b5aab-6c51-4834-a0c9-537209a484db
		summarizeBy: none
		sourceColumn: TradeType

		annotation SummarizationSetBy = Automatic

	column ActualMarginDollars
		dataType: double
		lineageTag: 6e62d97a-5c46-43f9-8abe-d4bf1a33b229
		summarizeBy: sum
		sourceColumn: ActualMarginDollars

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LowMarginFlag = ```
			
			LOOKUPVALUE(
			    dim_Parts_LowMargin[LowMarginFlag],
			    dim_Parts_LowMargin[PartNumber], [PartNumber],
			    dim_Parts_LowMargin[Branch], [Branch],
			    dim_Parts_LowMargin[Franchise], [Franchise],
			    BLANK()
			)
			
			```
		lineageTag: fccd75ed-99f7-4db9-a3fa-a5ce33f9b51e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column StockOrderPrice = ```
			
			IF(
			    ISBLANK([PartNumber]),
			    BLANK(),
			    VAR LookupResult = 
			        LOOKUPVALUE(
			            dim_Parts_LowMargin[StockOrderPrice],
			            dim_Parts_LowMargin[PartNumber], [PartNumber],
			            dim_Parts_LowMargin[Branch], [Branch],
			            dim_Parts_LowMargin[Franchise], [Franchise],
			            BLANK()
			        )
			    RETURN LookupResult
			)
			
			```
		lineageTag: 1816b48a-d1af-44df-a468-e177d94dd831
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ListPriceManuf = ```
			
			LOOKUPVALUE(
			    dim_Parts_LowMargin[ListPrice],
			    dim_Parts_LowMargin[PartNumber], [PartNumber],
			    dim_Parts_LowMargin[Branch], [Branch],
			    dim_Parts_LowMargin[Franchise], [Franchise],
			    BLANK()
			)
			
			```
		lineageTag: 3c36fb0c-32f0-4f91-a5d9-d6d600d92fab
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OriginalMarginDollars = ```
			
			VAR UnitSellPrice = [SaleValue] / [Qty]
			VAR UnitCost = 
			    LOOKUPVALUE(
			        dim_Parts_LowMargin[StockOrderPrice],
			        dim_Parts_LowMargin[PartNumber], [PartNumber],
			        dim_Parts_LowMargin[Branch], [Branch],
			        dim_Parts_LowMargin[Franchise], [Franchise],
			        BLANK()
			    )
			VAR OriginalMarginPerUnit = UnitSellPrice - UnitCost
			RETURN
			IF(
			    ISBLANK(UnitCost),
			    BLANK(),
			    OriginalMarginPerUnit * [Qty]
			)
			
			```
		lineageTag: 4a35a2a8-4a36-419b-a931-168a109efb1d
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column IsLowMarginFlagged = ```
			
			LOOKUPVALUE(
			    dim_Parts_LowMargin[IsLowMarginFlagged],
			    dim_Parts_LowMargin[PartNumber], [PartNumber],
			    dim_Parts_LowMargin[Branch], [Branch],
			    dim_Parts_LowMargin[Franchise], [Franchise],
			    FALSE()
			)
			
			```
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b466f7db-b6da-49de-8bd5-1ff8994c0c40
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column MarginDiscrepancyDollars = [ActualMarginDollars] - [OriginalMarginDollars]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: ac342b2b-53b1-488c-9ec0-12b91e7b24fc
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	partition Fact_InTrans = m
		mode: import
		source =
				/*
				============================================================================
				FACT_INTRANS - FOR POWER BI DIRECT IMPORT
				============================================================================
				Purpose: Parts sales transactions for low margin analysis
				Source: InTrans_Incremental table from Lakehouse
				Grain: One row per invoice transaction (TYPE = 'I')
				Expected Rows: 3-6M (2 years of invoices)
				Expected Refresh: 5-8 minutes
				============================================================================
				*/
				
				let
				    // ========================================================================
				    // STEP 1: CONNECT TO INTRANS_INCREMENTAL FROM LAKEHOUSE
				    // ========================================================================
				
				    Source = Sql.Database("xcrafcusadsu3d3wi4anbgp6we-gxnyznhdptpenfw724g3o5sjzm.datawarehouse.fabric.microsoft.com", "LH_Master_Data"),
				    dbo_InTrans_Incremental = Source{[Schema="dbo",Item="InTrans_Incremental"]}[Data],
				
				    // ========================================================================
				    // STEP 2: FILTER TO INVOICE TRANSACTIONS (TYPE = 'I')
				    // ========================================================================
				    /*
				    PERFORMANCE: Filter early to reduce row count by ~50%
				    BUSINESS LOGIC: Low margin analysis focuses on invoiced sales
				    */
				
				    FilterToInvoices = Table.SelectRows(dbo_InTrans_Incremental, each
				        [Type] = "I"
				    ),
				
				    // ========================================================================
				    // STEP 3: FILTER TO LAST 2 YEARS
				    // ========================================================================
				    /*
				    PERFORMANCE: Critical filter to reduce 6+ years to 2 years
				    Reduces row count from ~15M to 3-6M
				    Matches old report data scope
				    */
				
				    FilterDateRange = Table.SelectRows(FilterToInvoices, each
				        [TransDatetime] >= DateTime.From(Date.AddYears(DateTime.Date(DateTime.LocalNow()), -2))
				    ),
				
				    // ========================================================================
				    // STEP 4: SELECT ESSENTIAL COLUMNS
				    // ========================================================================
				    /*
				    PERFORMANCE: Only include columns needed for analysis
				    Reduces memory footprint and refresh time
				    */
				
				    SelectColumns = Table.SelectColumns(FilterDateRange, {
				        // Transaction keys
				        "TransId",
				        "RONumber",
				        "TransDatetime",
				
				        // Foreign keys for dimension joins
				        "Branch",
				        "PartNumber",
				        "Franchise",
				        "CustomerNo",
				        "Salesman",
				
				        // Transaction measures
				        "Type",
				        "Qty",
				        "SaleValue",
				        "CostValue",
				
				        // Additional context
				        "Description",
				        "TradeType"
				    }),
				
				    // ========================================================================
				    // STEP 5: PRE-CALCULATE ACTUAL MARGIN
				    // ========================================================================
				    /*
				    F4 OPTIMIZATION: Calculate once during refresh, not in DAX measures
				    Actual Margin = Sale $ - Cost $
				    */
				
				    AddActualMargin = Table.AddColumn(
				        SelectColumns,
				        "ActualMarginDollars",
				        each ([SaleValue] ?? 0) - ([CostValue] ?? 0),
				        type number
				    ),
				
				    // ========================================================================
				    // STEP 6: REMOVE DUPLICATES
				    // ========================================================================
				    /*
				    DATA QUALITY: Ensure unique transactions
				    */
				
				    RemoveDuplicates = Table.Distinct(AddActualMargin, {"TransId"}),
				
				    // ========================================================================
				    // STEP 7: FINAL DATA TYPES
				    // ========================================================================
				
				    FinalDataTypes = Table.TransformColumnTypes(RemoveDuplicates, {
				        {"TransId", Int64.Type},
				        {"RONumber", type text},
				        {"TransDatetime", type datetime},
				        {"Branch", type text},
				        {"PartNumber", type text},
				        {"Franchise", type text},
				        {"CustomerNo", type text},
				        {"Salesman", type text},
				        {"Type", type text},
				        {"Qty", type number},
				        {"SaleValue", type number},
				        {"CostValue", type number},
				        {"Description", type text},
				        {"TradeType", type text},
				        {"ActualMarginDollars", type number}
				    })
				
				in
				    FinalDataTypes
				
				/*
				============================================================================
				NEXT STEPS IN POWER BI:
				
				1. LOAD THIS QUERY TO MODEL
				
				2. CREATE RELATIONSHIPS:
				   - Fact_InTrans[TransDatetime] → dim_DateTable[Date] (ACTIVE)
				   - Fact_InTrans[Branch] → dim_BranchLocation[Branch] (ACTIVE)
				   - Fact_InTrans[PartNumber] → dim_Parts[PartNumber] (ACTIVE)
				   - Fact_InTrans[CustomerNo] → dim_CustomerList[CustomerNo] (ACTIVE)
				   - Fact_InTrans[PartNumber] → dim_Parts_LowMargin[PartNumber] (INACTIVE)
				
				3. ADD CALCULATED COLUMNS (in Fact_InTrans table):
				
				   LowMarginFlag =
				       RELATED(dim_Parts_LowMargin[LowMarginFlag])
				
				   StockOrderPrice =
				       RELATED(dim_Parts_LowMargin[StockOrderPrice])
				
				   ListPriceManuf =
				       RELATED(dim_Parts_LowMargin[ListPrice])
				
				   OriginalMarginDollars =
				       ([ListPriceManuf] - [StockOrderPrice]) * [Qty]
				
				   MarginDiscrepancyDollars =
				       [ActualMarginDollars] - [OriginalMarginDollars]
				
				   IsLowMarginFlagged =
				       [LowMarginFlag] = "LOW"
				
				4. CREATE BASE MEASURES:
				
				   Sale $ = SUM(Fact_InTrans[SaleValue])
				   Cost $ = SUM(Fact_InTrans[CostValue])
				   Qty = SUM(Fact_InTrans[Qty])
				
				   Actual Margin $ = SUM(Fact_InTrans[ActualMarginDollars])
				   Original Margin $ = SUM(Fact_InTrans[OriginalMarginDollars])
				   Margin Discrepancy $ = SUM(Fact_InTrans[MarginDiscrepancyDollars])
				
				   Actual Margin % = DIVIDE([Actual Margin $], [Sale $], 0)
				   Original Margin % = DIVIDE([Original Margin $], [Sale $], 0)
				
				5. VALIDATE:
				   - Check row count (should be 3-6M)
				   - Verify all Type = 'I'
				   - Spot check margin calculations
				   - Compare totals to old report
				
				Expected Refresh Time: 5-8 minutes (similar to old report)
				Expected Model Size: 500MB-1GB compressed
				============================================================================
				*/

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

