table 'Data Refresh'
	lineageTag: 4561a462-f702-485c-b224-bf1c0d077228

	column CurrentDateTime
		dataType: string
		lineageTag: 72a27470-4041-44c8-924e-724f99465db6
		summarizeBy: none
		sourceColumn: CurrentDateTime

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9bd0c296-9d89-4c53-9889-eea494a9a30b
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Time
		dataType: dateTime
		formatString: Long Time
		lineageTag: 1ae7ebe0-2879-4974-be0d-5edfadd2d5b3
		summarizeBy: none
		sourceColumn: Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	partition 'Data Refresh' = m
		mode: import
		source =
				let
				    // Fabric/Power BI Service runs in UTC — DateTime.LocalNow() returns UTC, not local time.
				    // DateTimeZone.SwitchZone converts UTC to Central Time with automatic DST handling.
				    UtcNow    = DateTimeZone.UtcNow(),
				    UtcDT     = DateTimeZone.RemoveZone(UtcNow),
				    CurYear   = Date.Year(DateTime.Date(UtcDT)),
				    Mar1      = #date(CurYear, 3, 1),
				    Sun1Mar   = Date.AddDays(Mar1, Number.Mod(7 - Date.DayOfWeek(Mar1, Day.Sunday), 7)),
				    DstStart  = #datetime(CurYear, 3, Date.Day(Date.AddDays(Sun1Mar, 7)), 8, 0, 0),
				    Nov1      = #date(CurYear, 11, 1),
				    Sun1Nov   = Date.AddDays(Nov1, Number.Mod(7 - Date.DayOfWeek(Nov1, Day.Sunday), 7)),
				    DstEnd    = #datetime(CurYear, 11, Date.Day(Sun1Nov), 7, 0, 0),
				    OffsetHrs = if UtcDT >= DstStart and UtcDT < DstEnd then -5 else -6,
				    LocalDT   = DateTimeZone.RemoveZone(DateTimeZone.SwitchZone(UtcNow, OffsetHrs, 0)),
				    Source    = #table({"CurrentDateTime"}, {{LocalDT}}),
				    AddDate   = Table.DuplicateColumn(Source, "CurrentDateTime", "Date"),
				    AddTime   = Table.DuplicateColumn(AddDate, "Date", "Time"),
				    ChgTypes  = Table.TransformColumnTypes(AddTime, {{"Date", type date}, {"Time", type time}})
				in
				    ChgTypes

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

