table 'Pagination Table'
	lineageTag: e8991a42-69e3-4a5f-8147-d08ba3f55805

	column 'Page Number'
		dataType: int64
		formatString: 0
		lineageTag: 2cd71769-c8b8-4892-b112-3751a7e1c0f0
		summarizeBy: sum
		sourceColumn: Page Number

		annotation SummarizationSetBy = Automatic

	column 'Min Row'
		dataType: int64
		formatString: 0
		lineageTag: 1ae7e38f-4f58-4826-9a52-e2930b6f3863
		summarizeBy: sum
		sourceColumn: Min Row

		annotation SummarizationSetBy = Automatic

	column 'Max Row'
		dataType: int64
		formatString: 0
		lineageTag: 7acb1027-3a21-48eb-a9ca-f1725663399a
		summarizeBy: sum
		sourceColumn: Max Row

		annotation SummarizationSetBy = Automatic

	partition 'Pagination Table' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSgWADpVidaCUjEBPEN4LwjUFMEN8YwjcBMUF8EyA/FgA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Page Number" = _t, #"Min Row" = _t, #"Max Row" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Page Number", Int64.Type}, {"Min Row", Int64.Type}, {"Max Row", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

